// Vital Factory Wavetables for Strudel
// Auto-generated by vital2strudel/convert_factory.py
//
// Usage: Copy this block to the top of your Strudel pattern,
// then use .s("wavetable_name") to select sounds.

await tables("https://raw.githubusercontent.com/strudel-dj/vital-wavetables/main/", 2048, {
  "_base": "https://raw.githubusercontent.com/strudel-dj/vital-wavetables/main/",
  "basic_shapes": ["basic_shapes.wav"],
  "classic_blend": ["classic_blend.wav"],
  "classic_fade": ["classic_fade.wav"],
  "harmonic_series": ["harmonic_series.wav"],
  "pulse_width": ["pulse_width.wav"],
  "quad_saw": ["quad_saw.wav"],
  "three_graces": ["three_graces.wav"],
  "low_high_fold": ["low_high_fold.wav"],
  "post_modern_pulse": ["post_modern_pulse.wav"],
  "saws_for_days": ["saws_for_days.wav"],
  "vital_sine_2": ["vital_sine_2.wav"],
  "vital_sine": ["vital_sine.wav"],
})

// Available wavetable sounds:
// basic_shapes, classic_blend, classic_fade, harmonic_series, pulse_width, quad_saw, three_graces, low_high_fold, post_modern_pulse, saws_for_days, vital_sine_2, vital_sine
//
// Example usage:
// note("c3 e3 g3 b3")
//   .s("basic_shapes")
//   .wt(sine(0.1, 0, 1))  // sweep through wavetable
//   .warp(0.3).warpmode("fold")
//   .unison(4).detune(0.2).spread(0.6)
//   .cutoff(2000).resonance(5)
//   .attack(0.3).decay(0.5).sustain(0.6).release(1.5)
//   .room(0.4).delay(0.2).delaytime(0.125)
