// Vital Preset: Ah Eh Ee Oh
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
note("c3 e3 g3 b3")
  .s("sawtooth")
  .warp(0.7)
  .unison(16)
  .detune(5.361)
  .spread(0.8)
  .gain(0.707)
  // envelope
  .attack(0.268)
  .decay(1)
  .release(0.548)
  // filter
  .cutoff(677)
  // effects
  .room(0.5)
  .roomsize(0.5)
  .shape(0.8)