// Vital Preset: FM Drum Circle
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("sawtooth")
    // envelope
    .attack(0.21)
    .decay(1)
    .release(0.548)
    // filter
    .cutoff(523)
    // effects
    .delay(0.333)
    .delaytime(4.5)
    .delayfeedback(0.5)
    .shape(0.8),
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .gain(0)
    // envelope
    .attack(0.21)
    .decay(1)
    .release(0.548)
    // filter
    .cutoff(523)
    // effects
    .delay(0.333)
    .delaytime(4.5)
    .delayfeedback(0.5)
    .shape(0.8),
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.5)
    .gain(0)
    // envelope
    .attack(0.21)
    .decay(1)
    .release(0.548)
    // filter
    .cutoff(523)
    // effects
    .delay(0.333)
    .delaytime(4.5)
    .delayfeedback(0.5)
    .shape(0.8)
)