// Vital Preset: Plucked String
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
note("c3 e3 g3 b3")
  // envelope
  .attack(0.115)
  .decay(0.936)
  .release(0.809)
  // filter
  .cutoff(261)
  .resonance(19.8)
  // effects
  .room(0.5)
  .roomsize(0.5)
  .delay(0.5)
  .delaytime(5)
  .delayfeedback(0.4)
  .shape(0.8)