// Vital Preset: Shepard Tone Template
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
note("c3 e3 g3 b3")
  .s("sawtooth")
  .warp(0.5)
  .unison(10)
  .detune(15.486)
  .spread(0.8)
  .gain(0.707)
  // envelope
  .attack(0.149)
  .decay(1)
  .release(0.548)
  // effects
  .room(0.5)
  .roomsize(0.5)
  .delay(0.333)
  .delaytime(4.5)
  .delayfeedback(0.5)
  .shape(0.8)