// Vital Preset: Staggered Phrases
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .unison(14)
    .detune(6.602)
    .spread(0.8)
    .pan(0.785)
    .gain(0.707)
    // envelope
    .attack(0.329)
    .decay(1)
    .release(0.548)
    // filter
    .cutoff(1589)
    .resonance(11.489)
    // effects
    .room(0.5)
    .roomsize(0.5)
    .delay(0.5)
    .delaytime(5)
    .delayfeedback(0.4)
    .shape(0.8),
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.5)
    .pan(0)
    // envelope
    .attack(0.329)
    .decay(1)
    .release(0.548)
    // filter
    .cutoff(1589)
    .resonance(11.489)
    // effects
    .room(0.5)
    .roomsize(0.5)
    .delay(0.5)
    .delaytime(5)
    .delayfeedback(0.4)
    .shape(0.8)
)