// Vital Preset: Touch Tone
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("sawtooth")
    // envelope
    .attack(0.218)
    .decay(1)
    .release(0.302)
    // effects
    .room(0.5)
    .roomsize(0.5)
    .delay(0.5)
    .delaytime(5)
    .delayfeedback(0.4)
    .shape(0.8),
  note("c3 e3 g3 b3")
    .s("sawtooth")
    // envelope
    .attack(0.218)
    .decay(1)
    .release(0.302)
    // effects
    .room(0.5)
    .roomsize(0.5)
    .delay(0.5)
    .delaytime(5)
    .delayfeedback(0.4)
    .shape(0.8)
)