// Vital Preset: untitled
// Auto-generated by vital2strudel

// Load wavetables
await tables("https://raw.githubusercontent.com/YOUR_REPO/main/wavetables/", 2048, {
  "_base": "https://raw.githubusercontent.com/YOUR_REPO/main/wavetables/",
  "untitled_osc2": ["untitled_osc2.wav"],
})

// Pattern — change the notes to taste!
note("c3 e3 g3 b3")
  .s("untitled_osc2")
  .wt(1)
  .warp(0.5)
  .unison(13)
  .detune(2.722)
  .spread(0.8)
  .gain(0.275)
  // envelope
  .decay(0.765)
  .sustain(0.005)
  .release(0.919)
  // filter
  .cutoff(133)
  .resonance(10)
  // effects
  .shape(0.38)