// Vital Preset: A happy ending of the world
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "a_happy_ending_of_the_world_osc3": ["a_happy_ending_of_the_world_osc3.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .unison(3)
    .spread(0.8)
    .gain(0.707)
    // envelope
    .attack(0.958)
    .decay(1)
    .sustain(0.55)
    .release(1.13)
    // filter
    .cutoff(261)
    .resonance(20)
    // modulation (osc1)
    .warp(0.5)
    .warpsync(0.5)
    .warpdepth(0.77)
    .tremolo(1)
    .tremolodepth(1)
    .tremoloshape("tri"),
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .unison(4)
    .spread(0.8)
    .gain(0.707)
    // envelope
    .attack(0.958)
    .decay(1)
    .sustain(0.55)
    .release(1.13)
    // filter
    .cutoff(261)
    .resonance(20)
    // modulation (osc2)
    .warp(0.5)
    .warpsync(0.5)
    .warpdepth(0.71)
    .tremolo(1)
    .tremolodepth(0.88)
    .tremoloshape("tri"),
  note("c3 e3 g3 b3")
    .s("a_happy_ending_of_the_world_osc3")
    .gain(0.83)
    // envelope
    .attack(0.958)
    .decay(1)
    .sustain(0.55)
    .release(1.13)
    // filter
    .cutoff(261)
    .resonance(20)
)

// === Unmapped modulations (Vital-specific) ===
// lfo_1 → chorus_mod_depth (amount: 0.645)
// random_1 → lfo_3_frequency (amount: 0.33)
// macro_control_1 → distortion_mix (amount: 1)
// macro_control_2 → reverb_dry_wet (amount: 0.9)
// macro_control_3 → delay_dry_wet (amount: 0.415)
// macro_control_4 → eq_high_cutoff (amount: -0.44)
// mod_wheel → filter_1_mix (amount: 1)
// macro_control_1 → modulation_11_amount (amount: 0.8)