// Vital Preset: A Night in Kalyan
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .gain(0.432)
    // envelope
    .attack(1.089)
    .decay(1.143)
    .sustain(0.65)
    .release(1.178)
    // filter
    .cutoff(1046)
    .resonance(20)
    // modulation (osc1)
    .wt(0)
    .wtrate(0.5)
    .wtdepth(0.72)
    .warp(0.5)
    .warprate(0.5)
    .warpdepth(0.197)
    // effects
    .room(0.25)
    .roomsize(0.5),
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.5)
    // envelope
    .attack(1.089)
    .decay(1.143)
    .sustain(0.65)
    .release(1.178)
    // filter
    .cutoff(1046)
    .resonance(20)
    // modulation (osc2)
    .wt(0.826)
    .wtrate(2.2)
    .wtdepth(0.875)
    // effects
    .room(0.25)
    .roomsize(0.5)
)

// === Unmapped modulations (Vital-specific) ===
// random_1 → lfo_4_smooth_time (amount: -0.36)
// random_2 → lfo_4_frequency (amount: -0.348)
// random_1 → osc_1_level (amount: 0.166)
// macro_control_1 → modulation_9_amount (amount: 0.227)
// macro_control_2 → lfo_4_frequency (amount: 0.214)
// macro_control_1 → modulation_13_amount (amount: 0.014)
// macro_control_3 → modulation_15_amount (amount: 0.031)
// macro_control_4 → reverb_dry_wet (amount: 0.75)