// Vital Preset: Abbysun
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.5)
    .warpmode("sync")
    .unison(16)
    .detune(4.472)
    .spread(0.8)
    .gain(0.707)
    // envelope
    .attack(1.422)
    .decay(1.654)
    .release(1.558)
    // filter
    .cutoff(261)
    .resonance(16.072)
    .ftype("24db")
    .lpenv(4.339)
    .lpattack(1.648)
    .lpdecay(1.916)
    .lpsustain(0.305)
    .lprelease(1.677)
    // effects
    .room(0.25)
    .roomsize(0.5)
    .delay(0.323)
    .delaytime(0.333)
    .delayfeedback(0.5),
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.5)
    .unison(3)
    .detune(3.3)
    .spread(1)
    .gain(0.707)
    // envelope
    .attack(1.422)
    .decay(1.654)
    .release(1.558)
    // filter
    .cutoff(261)
    .resonance(16.072)
    .ftype("24db")
    .lpenv(4.339)
    .lpattack(1.648)
    .lpdecay(1.916)
    .lpsustain(0.305)
    .lprelease(1.677)
    // modulation (osc3)
    .tremolo(0.5)
    .tremolodepth(0.32)
    .tremoloshape("tri")
    // effects
    .room(0.25)
    .roomsize(0.5)
    .delay(0.323)
    .delaytime(0.333)
    .delayfeedback(0.5)
)

// === Unmapped modulations (Vital-specific) ===
// velocity → modulation_1_amount (amount: 0.289)
// env_2 → osc_2_level (amount: 0.648)
// macro_control_1 → env_1_attack (amount: -0.178)
// macro_control_1 → env_2_delay (amount: -0.59)
// macro_control_1 → env_2_attack (amount: -0.013)
// macro_control_4 → reverb_dry_wet (amount: 0.258)
// macro_control_4 → reverb_decay_time (amount: 0.164)
// lfo_2 → env_2_sustain (amount: 0.132)