// Vital Preset: Ah Eh Ee Oh
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
note("c3 e3 g3 b3")
  .s("sawtooth")
  .warp(0.7)
  .unison(16)
  .detune(1.072)
  .spread(0.8)
  .gain(0.707)
  // envelope
  .attack(0.268)
  .decay(1)
  .release(0.548)
  // filter
  .cutoff(677)
  // modulation
  .wt(0)
  .wtsync(64)
  .wtdepth(0.22)

// === Unmapped modulations (Vital-specific) ===
// random_1 → osc_1_wave_frame (amount: 0.74)
// random_2 → osc_1_spectral_morph_amount (amount: 0.6)
// macro_control_1 → osc_1_spectral_morph_amount (amount: 0.5)
// macro_control_2 → delay_dry_wet (amount: 0.667)
// mod_wheel → filter_1_cutoff (amount: 0.489)
// mod_wheel → filter_2_cutoff (amount: -0.432)
// macro_control_3 → filter_1_cutoff (amount: 0.465)
// macro_control_3 → filter_2_cutoff (amount: 0.621)