// Vital Preset: Analog Pad
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "analog_pad_osc2": ["analog_pad_osc2.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.5)
    .unison(7)
    .detune(3.022)
    .spread(0.8)
    .gain(0.305)
    // envelope
    .attack(0.518)
    .decay(1.057)
    .sustain(0.611)
    .release(0.892)
    // filter
    .cutoff(100)
    // modulation (osc1)
    .wt(0)
    .wtsync(2)
    .wtdepth(1),
  note("c3 e3 g3 b3")
    .s("analog_pad_osc2")
    .warp(0.403)
    .warpmode("bendmp")
    .gain(0.15)
    // envelope
    .attack(0.518)
    .decay(1.057)
    .sustain(0.611)
    .release(0.892)
    // filter
    .cutoff(100)
)

// === Unmapped modulations (Vital-specific) ===
// macro_control_1 → filter_1_cutoff (amount: 0.311)
// random_1 → osc_2_distortion_amount (amount: 0.155)
// velocity → osc_1_level (amount: 0.84)
// velocity → osc_2_level (amount: 0.41)
// macro_control_2 → reverb_dry_wet (amount: 0.46)
// macro_control_3 → delay_dry_wet (amount: 0.25)
// macro_control_4 → distortion_drive (amount: 0.295)