// Vital Preset: Banana Wob
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "banana_wob_osc2": ["banana_wob_osc2.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(1)
    .warpmode("spin")
    .gain(0.707)
    // envelope
    .decay(1)
    .release(0.416)
    // filter
    .cutoff(54)
    .resonance(9.819)
    // effects
    .shape(0.344),
  note("c3 e3 g3 b3")
    .s("banana_wob_osc2")
    .warp(0.5)
    .gain(0.707)
    // envelope
    .decay(1)
    .release(0.416)
    // filter
    .cutoff(54)
    .resonance(9.819)
    // effects
    .shape(0.344)
)

// === Unmapped modulations (Vital-specific) ===
// macro_control_1 → osc_1_wave_frame (amount: 0.104)
// macro_control_1 → filter_1_cutoff (amount: 0.381)
// macro_control_1 → distortion_filter_cutoff (amount: 0.48)
// macro_control_1 → phaser_center (amount: -0.342)
// macro_control_1 → chorus_dry_wet (amount: 0.272)
// macro_control_1 → eq_low_cutoff (amount: 0.156)
// macro_control_1 → osc_1_level (amount: 1)
// macro_control_1 → phaser_dry_wet (amount: 0.624)