// Vital Preset: Big Stomp
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "big_stomp_osc2": ["big_stomp_osc2.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("triangle")
    .warp(0.68)
    .warpmode("bendm")
    .unison(3)
    .spread(0.64)
    .gain(0.75)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.548)
    // filter
    .cutoff(679)
    .lpenv(-1.798)
    .lpdecay(0.845)
    .lprelease(0.548)
    // modulation (osc1)
    .tremolosync(16)
    .tremolodepth(0.297)
    .wtenv(0.72)
    .wtdecay(1.327)
    .wtrelease(0.548)
    // effects
    .shape(0.18),
  note("c3 e3 g3 b3")
    .s("big_stomp_osc2")
    .wt(0.594)
    .warp(0.5)
    .gain(0.707)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.548)
    // filter
    .cutoff(679)
    .lpenv(-1.798)
    .lpdecay(0.845)
    .lprelease(0.548)
    // effects
    .shape(0.18)
)

// === Unmapped modulations (Vital-specific) ===
// env_3 → filter_1_blend_transpose (amount: 0.6)
// stereo → filter_1_cutoff (amount: -0.01)
// env_2 → osc_2_transpose (amount: 0.5)
// env_2 → osc_1_transpose (amount: 0.5)
// env_4 → osc_1_unison_detune (amount: 0.99)
// macro_control_1 → env_2_decay (amount: 0.135)
// macro_control_2 → env_2_attack (amount: 0.24)
// macro_control_2 → macro_control_1 (amount: 1)