// Vital Preset: Boot Scre3n
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "boot_scre3n_osc2": ["boot_scre3n_osc2.wav"],
  "boot_scre3n_osc3": ["boot_scre3n_osc3.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .gain(0.707)
    // envelope
    .attack(0.625)
    .decay(0.667)
    .release(0.75)
    // modulation (osc1)
    .warp(0.5)
    .warpsync(16)
    .warpdepth(0.13)
    .warpshape("sine")
    // effects
    .room(0.41)
    .roomsize(0.78),
  note("c3 e3 g3 b3")
    .s("boot_scre3n_osc2")
    .warpmode("sync")
    .unison(2)
    .detune(3.522)
    .spread(0.8)
    .gain(0.707)
    // envelope
    .attack(0.625)
    .decay(0.667)
    .release(0.75)
    // modulation (osc2)
    .warp(0.5)
    .warpsync(16)
    .warpdepth(0.14)
    .warpshape("sine")
    // effects
    .room(0.41)
    .roomsize(0.78),
  note("c3 e3 g3 b3")
    .s("boot_scre3n_osc3")
    .unison(3)
    .detune(4.472)
    .spread(0.925)
    .gain(0.677)
    // envelope
    .attack(0.625)
    .decay(0.667)
    .release(0.75)
    // modulation (osc3)
    .warpenv(0.64)
    .warpattack(0.994)
    .warpdecay(1)
    .warpsustain(1)
    .warprelease(0.976)
    // effects
    .room(0.41)
    .roomsize(0.78)
)

// === Unmapped modulations (Vital-specific) ===
// env_2 → osc_3_unison_detune (amount: -0.127)
// macro_control_1 → osc_1_spectral_morph_amount (amount: 0.06)
// macro_control_1 → osc_1_level (amount: 0.253)
// macro_control_2 → osc_2_spectral_morph_amount (amount: -0.45)
// macro_control_2 → osc_2_distortion_amount (amount: 0.45)
// macro_control_2 → osc_1_transpose (amount: 0.05)
// macro_control_2 → osc_2_level (amount: -0.087)
// macro_control_3 → distortion_drive (amount: 0.22)