// Vital Preset: Ceramic
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "ceramic_osc1": ["ceramic_osc1.wav"],
})

// Pattern — change the notes to taste!
note("c3 e3 g3 b3")
  .s("ceramic_osc1")
  .warp(0.998)
  .warpmode("quant")
  .gain(0.232)
  // envelope
  .attack(0.149)
  .decay(0.616)
  .sustain(0.328)
  .release(0.749)
  // filter
  .cutoff(2774)
  .resonance(18.428)
  // modulation
  .lpsync(16)
  .lpdepth(1334)
  .lpdc(0)
  .lpshape("sine")
  // effects
  .room(0.261)
  .roomsize(0.26)
  .shape(0.18)

// === Unmapped modulations (Vital-specific) ===
// macro_control_1 → filter_1_resonance (amount: 0.25)
// macro_control_1 → filter_2_resonance (amount: -0.996)
// macro_control_1 → filter_fx_cutoff (amount: 0.469)
// macro_control_1 → env_1_release (amount: -0.16)
// macro_control_1 → env_1_decay (amount: -0.108)
// macro_control_1 → env_1_sustain (amount: -0.502)
// macro_control_2 → lfo_1_fade_time (amount: -1)
// macro_control_2 → filter_1_cutoff (amount: 0.086)