// Vital Preset: Chorusy Keys
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.5)
    .unison(16)
    .detune(2.1)
    .spread(1)
    .gain(0.74)
    // envelope
    .attack(0.149)
    .decay(0.643)
    .sustain(0.295)
    // filter
    .cutoff(373)
    .resonance(2.118)
    // modulation (osc1)
    .wt(0)
    .wtsync(16)
    .wtdepth(0.52),
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .unison(8)
    .detune(2.222)
    .spread(1)
    .gain(0.517)
    // envelope
    .attack(0.149)
    .decay(0.643)
    .sustain(0.295)
    // filter
    .cutoff(373)
    .resonance(2.118)
    // modulation (osc2)
    .warp(0.5)
    .warpsync(16)
    .warpdepth(0.43)
)

// === Unmapped modulations (Vital-specific) ===
// env_2 → chorus_feedback (amount: 0.36)
// macro_control_1 → env_1_release (amount: 0.3)
// lfo_2 → voice_tune (amount: 1)
// macro_control_2 → filter_2_blend (amount: -0.6)
// macro_control_2 → filter_1_blend (amount: 0.5)
// mod_wheel → filter_fx_cutoff (amount: 1)
// macro_control_4 → delay_dry_wet (amount: 0.22)
// macro_control_3 → osc_2_distortion_amount (amount: 1)