// Vital Preset: Complex Electro 1
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "complex_electro_1_osc2": ["complex_electro_1_osc2.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .gain(0.707)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.548)
    // filter
    .cutoff(21096)
    // modulation (osc1)
    .tremolosync(4)
    .tremolodepth(0.6)
    .tremoloshape("tri")
    .lpsync(4)
    .lpdepth(0)
    .lpdc(0)
    // effects
    .room(0.065)
    .roomsize(0.245),
  note("c3 e3 g3 b3")
    .s("complex_electro_1_osc2")
    .warp(0.5)
    .unison(3)
    .spread(1)
    .gain(0.707)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.548)
    // filter
    .cutoff(21096)
    // modulation
    .lpsync(4)
    .lpdepth(0)
    .lpdc(0)
    // effects
    .room(0.065)
    .roomsize(0.245),
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.5)
    .gain(0.707)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.548)
    // filter
    .cutoff(21096)
    // modulation (osc3)
    .wt(0)
    .wtsync(32)
    .wtdepth(1)
    .lpsync(4)
    .lpdepth(0)
    .lpdc(0)
    // effects
    .room(0.065)
    .roomsize(0.245)
)

// === Unmapped modulations (Vital-specific) ===
// macro_control_1 → filter_1_cutoff (amount: -0.81)
// macro_control_2 → modulation_6_amount (amount: 0.199)
// macro_control_2 → volume (amount: -0.37)
// macro_control_3 → osc_1_wave_frame (amount: 1)
// macro_control_3 → osc_1_spectral_morph_amount (amount: -0.53)
// note → macro_control_3 (amount: 0.28)
// macro_control_4 → distortion_mix (amount: 0.58)
// mod_wheel → filter_1_cutoff (amount: 1)