// Vital Preset: corrupted_...+=boot-_
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
note("c3 e3 g3 b3")
  .s("sawtooth")
  .unison(16)
  .detune(3.2)
  .spread(0.8)
  .gain(0.745)
  // envelope
  .attack(1.267)
  .decay(1.19)
  .sustain(0.745)
  .release(0.856)
  // filter
  .cutoff(261)
  // modulation
  .wt(0)
  .wtsync(2)
  .wtdepth(1)
  // effects
  .coarse(4)

// === Unmapped modulations (Vital-specific) ===
// macro_control_1 → delay_dry_wet (amount: 0.53)
// macro_control_1 → reverb_dry_wet (amount: 1)
// random_1 → phaser_center (amount: 0.042)
// random_1 → lfo_1_phase (amount: 1)
// env_1 → phaser_dry_wet (amount: 1)
// lfo_3 → phaser_mod_depth (amount: 0.26)
// macro_control_2 → chorus_dry_wet (amount: 1)
// env_1 → filter_fx_resonance (amount: 0.332)