// Vital Preset: Crescendo Bells
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "crescendo_bells_osc1": ["crescendo_bells_osc1.wav"],
  "crescendo_bells_osc2": ["crescendo_bells_osc2.wav"],
  "crescendo_bells_osc3": ["crescendo_bells_osc3.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("crescendo_bells_osc1")
    .warp(0.5)
    .gain(0.707)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(1.154)
    // filter
    .cutoff(643)
    .resonance(6.19)
    // modulation (osc1)
    .tremolosync(8)
    .tremolodepth(0.77)
    .tremoloshape("tri")
    .lpsync(8)
    .lpdepth(12465)
    .lpdc(0)
    // effects
    .room(0.465)
    .roomsize(0.605)
    .delay(0.258)
    .delaytime(0.333)
    .delayfeedback(0.5),
  note("c3 e3 g3 b3")
    .s("crescendo_bells_osc2")
    .wt(0.073)
    .warp(0.5)
    .gain(0.707)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(1.154)
    // filter
    .cutoff(643)
    .resonance(6.19)
    // modulation (osc2)
    .tremolosync(8)
    .tremolodepth(0.83)
    .tremoloshape("tri")
    .lpsync(8)
    .lpdepth(12465)
    .lpdc(0)
    // effects
    .room(0.465)
    .roomsize(0.605)
    .delay(0.258)
    .delaytime(0.333)
    .delayfeedback(0.5),
  note("c3 e3 g3 b3")
    .s("crescendo_bells_osc3")
    .wt(0.161)
    .warp(0.5)
    .gain(0.707)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(1.154)
    // filter
    .cutoff(643)
    .resonance(6.19)
    // modulation (osc3)
    .tremolosync(8)
    .tremolodepth(0.82)
    .tremoloshape("tri")
    .lpsync(8)
    .lpdepth(12465)
    .lpdc(0)
    // effects
    .room(0.465)
    .roomsize(0.605)
    .delay(0.258)
    .delaytime(0.333)
    .delayfeedback(0.5)
)

// === Unmapped modulations (Vital-specific) ===
// macro_control_2 → flanger_dry_wet (amount: 0.78)
// macro_control_1 → lfo_2_delay_time (amount: -0.09)
// macro_control_1 → lfo_3_delay_time (amount: -0.18)
// velocity → volume (amount: 0.165)
// velocity → reverb_dry_wet (amount: 0.175)
// velocity → delay_dry_wet (amount: 0.107)
// velocity → sample_level (amount: 0.135)
// macro_control_3 → osc_2_wave_frame (amount: 0.157)