// Vital Preset: Cursed Steps
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "cursed_steps_osc1": ["cursed_steps_osc1.wav"],
  "cursed_steps_osc2": ["cursed_steps_osc2.wav"],
  "cursed_steps_osc3": ["cursed_steps_osc3.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("cursed_steps_osc1")
    .unison(3)
    .detune(4.222)
    .spread(0.8)
    .gain(0.61)
    // envelope
    .attack(0.149)
    .decay(1)
    // filter
    .cutoff(86)
    .resonance(9.935)
    .ftype("24db")
    // modulation (osc1)
    .warp(0.5)
    .warpsync(16)
    .warpdepth(0.54)
    .tremolosync(16)
    .tremolodepth(0.89)
    .tremoloshape("tri")
    .lpsync(4)
    .lpdepth(4581)
    .lpdc(0)
    // effects
    .room(0.515)
    .roomsize(0.54)
    .shape(0.04),
  note("c3 e3 g3 b3")
    .s("cursed_steps_osc2")
    .warp(0.5)
    .unison(3)
    .detune(5.75)
    .spread(0.8)
    .gain(0.707)
    // envelope
    .attack(0.149)
    .decay(1)
    // filter
    .cutoff(86)
    .resonance(9.935)
    .ftype("24db")
    // modulation (osc2)
    .tremolosync(16)
    .tremolodepth(0.46)
    .tremoloshape("tri")
    .lpsync(4)
    .lpdepth(4581)
    .lpdc(0)
    // effects
    .room(0.515)
    .roomsize(0.54)
    .shape(0.04),
  note("c3 e3 g3 b3")
    .s("cursed_steps_osc3")
    .wt(0.466)
    .warp(0.5)
    .unison(3)
    .detune(3.372)
    .spread(0.8)
    .gain(0.42)
    // envelope
    .attack(0.149)
    .decay(1)
    // filter
    .cutoff(86)
    .resonance(9.935)
    .ftype("24db")
    // modulation
    .lpsync(4)
    .lpdepth(4581)
    .lpdc(0)
    // effects
    .room(0.515)
    .roomsize(0.54)
    .shape(0.04)
)

// === Unmapped modulations (Vital-specific) ===
// lfo_2 → osc_1_transpose (amount: 0.5)
// macro_control_1 → filter_fx_cutoff (amount: 0.459)
// macro_control_2 → osc_3_transpose (amount: 0.26)
// macro_control_3 → osc_2_transpose (amount: 0.5)
// random_1 → macro_control_2 (amount: 0.93)
// random_2 → macro_control_3 (amount: 0.475)
// macro_control_4 → compressor_attack (amount: 1)
// macro_control_4 → compressor_release (amount: 0.99)