// Vital Preset: Damped Horn
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "damped_horn_osc2": ["damped_horn_osc2.wav"],
  "damped_horn_osc3": ["damped_horn_osc3.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.5)
    .unison(8)
    .detune(1.722)
    .spread(0.8)
    .gain(0.452)
    // envelope
    .attack(0.863)
    .decay(1)
    .release(0.548)
    // filter
    .cutoff(12)
    .resonance(4.095)
    // modulation (osc1)
    .wt(0)
    .wtsync(16)
    .wtdepth(1)
    .lpsync(16)
    .lpdepth(1363)
    .lpdc(0)
    // effects
    .room(0.33)
    .roomsize(0.5)
    .delay(0.163)
    .delaytime(0.333)
    .delayfeedback(0.35)
    .shape(0.1),
  note("c3 e3 g3 b3")
    .s("damped_horn_osc2")
    .warp(0.5)
    .unison(7)
    .detune(4.672)
    .spread(0.33)
    .gain(0.15)
    // envelope
    .attack(0.863)
    .decay(1)
    .release(0.548)
    // filter
    .cutoff(12)
    .resonance(4.095)
    // modulation
    .lpsync(16)
    .lpdepth(1363)
    .lpdc(0)
    // effects
    .room(0.33)
    .roomsize(0.5)
    .delay(0.163)
    .delaytime(0.333)
    .delayfeedback(0.35)
    .shape(0.1),
  note("c3 e3 g3 b3")
    .s("damped_horn_osc3")
    .warp(0.5)
    .unison(6)
    .detune(4.572)
    .spread(0.305)
    .gain(0.707)
    // envelope
    .attack(0.863)
    .decay(1)
    .release(0.548)
    // filter
    .cutoff(12)
    .resonance(4.095)
    // modulation
    .lpsync(16)
    .lpdepth(1363)
    .lpdc(0)
    // effects
    .room(0.33)
    .roomsize(0.5)
    .delay(0.163)
    .delaytime(0.333)
    .delayfeedback(0.35)
    .shape(0.1)
)

// === Unmapped modulations (Vital-specific) ===
// lfo_3 → voice_tune (amount: -0.276)
// lfo_4 → voice_tune (amount: 0.276)
// macro_control_1 → lfo_4_smooth_time (amount: -0.99)
// velocity → filter_2_cutoff (amount: 0.55)
// macro_control_2 → lfo_5_smooth_time (amount: -0.93)
// velocity → filter_1_cutoff (amount: 0.81)
// env_2 → osc_2_unison_detune (amount: 0.093)
// macro_control_3 → osc_3_level (amount: -0.13)