// Vital Preset: Destruction
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "destruction_osc1": ["destruction_osc1.wav"],
  "destruction_osc2": ["destruction_osc2.wav"],
  "destruction_osc3": ["destruction_osc3.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("destruction_osc1")
    .warp(0.61)
    .warpmode("fold")
    .unison(16)
    .detune(4.472)
    .spread(0.8)
    .gain(0.707)
    // envelope
    .attack(0.534)
    .decay(1)
    .release(0.441)
    // filter
    .cutoff(636)
    .ftype("24db")
    .lpenv(1.776)
    .lpattack(0.934)
    .lpdecay(1)
    .lprelease(1.154)
    // modulation
    .lpsync(8)
    .lpdepth(2908)
    .lpdc(0)
    .delay(tri.fast(8).range(0, 0.695))
    // effects
    .shape(0.19),
  note("c3 e3 g3 b3")
    .s("destruction_osc2")
    .warp(0.5)
    .warpmode("fold")
    .gain(0.34)
    // envelope
    .attack(0.534)
    .decay(1)
    .release(0.441)
    // filter
    .cutoff(636)
    .ftype("24db")
    .lpenv(1.776)
    .lpattack(0.934)
    .lpdecay(1)
    .lprelease(1.154)
    // modulation (osc2)
    .tremolosync(4)
    .tremolodepth(1)
    .tremoloshape("tri")
    .warpenv(0.078)
    .warpattack(0.756)
    .warpdecay(0.905)
    .warprelease(1.178)
    .wtenv(0.76)
    .wtattack(0.756)
    .wtdecay(0.905)
    .wtrelease(1.178)
    .lpsync(8)
    .lpdepth(2908)
    .lpdc(0)
    .delay(tri.fast(8).range(0, 0.695))
    // effects
    .shape(0.19),
  note("c3 e3 g3 b3")
    .s("destruction_osc3")
    .warp(0.5)
    .gain(0.622)
    // envelope
    .attack(0.534)
    .decay(1)
    .release(0.441)
    // filter
    .cutoff(636)
    .ftype("24db")
    .lpenv(1.776)
    .lpattack(0.934)
    .lpdecay(1)
    .lprelease(1.154)
    // modulation
    .lpsync(8)
    .lpdepth(2908)
    .lpdc(0)
    .delay(tri.fast(8).range(0, 0.695))
    // effects
    .shape(0.19)
)

// === Unmapped modulations (Vital-specific) ===
// env_2 → osc_1_tune (amount: -0.5)
// stereo → filter_1_cutoff (amount: 0.036)
// env_4 → modulation_4_amount (amount: 0.171)
// stereo → osc_1_wave_frame (amount: 1)
// stereo → osc_1_level (amount: -0.28)
// lfo_1 → filter_1_blend (amount: 0.991)
// env_2 → osc_2_tune (amount: -0.5)
// mod_wheel → stereo_routing (amount: 0.292)