// Vital Preset: Digestive Trauma
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("triangle")
    .warpmode("bendm")
    .gain(0.707)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.548)
    // filter
    .cutoff(261)
    // modulation (osc1)
    .wt(0)
    .wtsync(16)
    .wtdepth(0.87)
    .wtshape("sine")
    .warp(0.5)
    .warpsync(16)
    .warpdepth(0.33)
    .warpshape("sine")
    // effects
    .shape(0.08),
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.5)
    .gain(0.707)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.548)
    // filter
    .cutoff(261)
    // modulation (osc3)
    .wt(0)
    .wtsync(16)
    .wtdepth(0.28)
    .wtshape("sine")
    // effects
    .shape(0.08)
)

// === Unmapped modulations (Vital-specific) ===
// lfo_2 → distortion_drive (amount: -0.16)
// macro_control_1 → osc_1_spectral_morph_amount (amount: 0.32)
// macro_control_2 → modulation_2_amount (amount: 0.141)
// macro_control_2 → filter_2_cutoff (amount: -0.298)
// macro_control_2 → filter_2_resonance (amount: 0.425)
// macro_control_2 → modulation_5_amount (amount: 0.164)
// macro_control_2 → distortion_filter_cutoff (amount: -0.35)
// macro_control_2 → distortion_filter_resonance (amount: 0.425)