// Vital Preset: Digital roller
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "digital_roller_osc1": ["digital_roller_osc1.wav"],
  "digital_roller_osc2": ["digital_roller_osc2.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("digital_roller_osc1")
    .warp(0.445)
    .warpmode("bendp")
    .gain(0.707)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.548)
    // modulation (osc1)
    .wt(0.044)
    .wtsync(8)
    .wtdepth(1)
    .lpsync(8)
    .lpdepth(18000)
    .lpdc(0)
    // effects
    .shape(0.48),
  note("c3 e3 g3 b3")
    .s("digital_roller_osc2")
    .gain(0.8)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.548)
    // modulation
    .lpsync(8)
    .lpdepth(18000)
    .lpdc(0)
    // effects
    .shape(0.48)
)

// === Unmapped modulations (Vital-specific) ===
// lfo_2 → filter_fx_blend_transpose (amount: 0.75)
// lfo_2 → osc_2_transpose (amount: 0.5)
// lfo_2 → osc_1_transpose (amount: -0.1)
// macro_control_1 → chorus_dry_wet (amount: 0.25)
// macro_control_2 → osc_2_distortion_amount (amount: 0.285)
// macro_control_2 → modulation_10_amount (amount: 0.243)
// macro_control_1 → modulation_11_amount (amount: -0.035)