// Vital Preset: Dispersed Grit
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("triangle")
    .warpmode("bendmp")
    .gain(0.675)
    // envelope
    .attack(0.25)
    .decay(0.523)
    .sustain(0.765)
    .release(0.25)
    // modulation (osc1)
    .warp(1)
    .warpsync(4)
    .warpdepth(0.585)
    // effects
    .shape(0.33),
  note("c3 e3 g3 b3")
    .s("sawtooth")
    // envelope
    .attack(0.25)
    .decay(0.523)
    .sustain(0.765)
    .release(0.25)
    // modulation (osc2)
    .warp(0.005)
    .warpsync(4)
    .warpdepth(0.77)
    // effects
    .shape(0.33)
)

// === Unmapped modulations (Vital-specific) ===
// macro_control_1 → osc_2_distortion_amount (amount: 0.495)
// macro_control_3 → lfo_1_stereo (amount: 0.5)
// mod_wheel → filter_fx_cutoff (amount: 0.594)
// mod_wheel → lfo_1_tempo (amount: 0.21)
// macro_control_4 → reverb_dry_wet (amount: 0.51)
// macro_control_2 → phaser_dry_wet (amount: 1)
// mod_wheel → phaser_tempo (amount: -0.4)
// velocity → modulation_6_amount (amount: 0.442)