// Vital Preset: Disrupt
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "disrupt_osc1": ["disrupt_osc1.wav"],
  "disrupt_osc2": ["disrupt_osc2.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("disrupt_osc1")
    .warp(0.724)
    .warpmode("bendp")
    .unison(16)
    .detune(4.472)
    .spread(0.8)
    .gain(0.707)
    // envelope
    .attack(0.149)
    .decay(1)
    .sustain(0.767)
    .release(0.876)
    // filter
    .cutoff(897)
    .resonance(10.396)
    .ftype("24db")
    // modulation (osc1)
    .wtenv(1)
    .wtattack(0.149)
    .wtdecay(0.981)
    .wtrelease(1.013)
    // effects
    .room(0.117)
    .roomsize(0.5)
    .delay(0.133)
    .delaytime(0.25)
    .delayfeedback(0.268)
    .shape(0.411),
  note("c3 e3 g3 b3")
    .s("disrupt_osc2")
    .unison(16)
    .detune(3.468)
    .spread(0.8)
    .gain(0.707)
    // envelope
    .attack(0.149)
    .decay(1)
    .sustain(0.767)
    .release(0.876)
    // filter
    .cutoff(897)
    .resonance(10.396)
    .ftype("24db")
    // modulation (osc2)
    .warp(0.5)
    .warpsync(16)
    .warpdepth(1)
    .tremolosync(16)
    .tremolodepth(0.971)
    .tremoloshape("tri")
    .wtenv(1)
    .wtattack(0.149)
    .wtdecay(1.484)
    .wtrelease(1.063)
    .warpenv(0.555)
    .warpattack(0.149)
    .warpdecay(0.675)
    .warprelease(0.86)
    // effects
    .room(0.117)
    .roomsize(0.5)
    .delay(0.133)
    .delaytime(0.25)
    .delayfeedback(0.268)
    .shape(0.411),
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warpmode("fold")
    // envelope
    .attack(0.149)
    .decay(1)
    .sustain(0.767)
    .release(0.876)
    // filter
    .cutoff(897)
    .resonance(10.396)
    .ftype("24db")
    // modulation (osc3)
    .warp(0.131)
    .warpsync(2)
    .warpdepth(0.869)
    .wt(0)
    .wtsync(4)
    .wtdepth(1)
    // effects
    .room(0.117)
    .roomsize(0.5)
    .delay(0.133)
    .delaytime(0.25)
    .delayfeedback(0.268)
    .shape(0.411)
)

// === Unmapped modulations (Vital-specific) ===
// env_4 → osc_1_level (amount: 1)
// note → osc_3_spectral_morph_amount (amount: -0.598)
// random_1 → eq_band_cutoff (amount: 0.523)
// random_2 → eq_band_gain (amount: 0.393)
// env_4 → osc_1_transpose (amount: 0.628)
// random_3 → filter_2_cutoff (amount: -0.186)
// random_4 → filter_1_cutoff (amount: -0.258)
// note → modulation_12_power (amount: -0.321)