// Vital Preset: Distant Majestic Lead
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
note("c3 e3 g3 b3")
  .s("sawtooth")
  .warp(0.495)
  .unison(8)
  .spread(0.8)
  .gain(0.707)
  // envelope
  .attack(0.274)
  .decay(0.89)
  .sustain(0.064)
  // filter
  .cutoff(21096)

// === Unmapped modulations (Vital-specific) ===
// velocity → osc_1_level (amount: 1)
// note → filter_1_cutoff (amount: -0.25)
// macro_control_1 → reverb_dry_wet (amount: 1)
// macro_control_2 → delay_dry_wet (amount: 0.207)
// macro_control_3 → filter_fx_cutoff (amount: 0.402)
// macro_control_3 → filter_fx_mix (amount: 0.488)
// macro_control_4 → env_1_release (amount: 1)