// Vital Preset: DIY
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
note("c3 e3 g3 b3")
  .s("sawtooth")
  .warp(0.5)
  .unison(8)
  .gain(0.4)
  // envelope
  .attack(0.084)
  .decay(1)
  .release(0.94)
  // filter
  .cutoff(523)
  .resonance(18.378)
  .ftype("24db")
  // modulation
  .wt(0.865)
  .wtrate(0.202)
  .wtdepth(0.84)
  // effects
  .room(0.485)
  .roomsize(0.595)
  .shape(0.211)

// === Unmapped modulations (Vital-specific) ===
// mod_wheel → filter_2_cutoff (amount: -0.186)
// mod_wheel → sample_level (amount: 0.215)
// velocity → osc_1_level (amount: 0.636)
// velocity → modulation_5_amount (amount: 0.184)
// macro_control_4 → reverb_decay_time (amount: 0.253)
// stereo → osc_1_unison_blend (amount: 1)
// stereo → osc_1_unison_detune (amount: 1)
// env_3 → osc_3_transpose (amount: 0.289)