// Vital Preset: Drowning Machine
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .unison(3)
    .detune(1.872)
    .spread(0.8)
    .gain(0.707)
    // envelope
    .decay(0.774)
    .sustain(0.9)
    .release(1.297)
    // filter
    .cutoff(1243)
    .resonance(10.677)
    .ftype("ladder")
    // modulation (osc1)
    .warpenv(0.5)
    .warpattack(0.844)
    .warpdecay(1.155)
    .warpsustain(0.195)
    .warprelease(0.548)
    // effects
    .shape(0.08),
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .unison(3)
    .detune(2.05)
    .spread(0.8)
    .gain(0.707)
    // envelope
    .decay(0.774)
    .sustain(0.9)
    .release(1.297)
    // filter
    .cutoff(1243)
    .resonance(10.677)
    .ftype("ladder")
    // modulation (osc2)
    .warpenv(0.5)
    .warpattack(0.844)
    .warpdecay(1.155)
    .warpsustain(0.195)
    .warprelease(0.548)
    // effects
    .shape(0.08),
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.5)
    .gain(0.707)
    // envelope
    .decay(0.774)
    .sustain(0.9)
    .release(1.297)
    // filter
    .cutoff(1243)
    .resonance(10.677)
    .ftype("ladder")
    // modulation (osc3)
    .warpenv(0.49)
    .warpattack(0.844)
    .warpdecay(1.155)
    .warpsustain(0.195)
    .warprelease(0.548)
    // effects
    .shape(0.08)
)

// === Unmapped modulations (Vital-specific) ===
// velocity → modulation_3_amount (amount: 0.29)
// env_1 → compressor_high_gain (amount: 0.283)
// macro_control_1 → env_1_attack (amount: 0.865)
// macro_control_2 → modulation_8_amount (amount: -0.1)
// macro_control_2 → modulation_9_amount (amount: 0.135)
// macro_control_2 → modulation_10_amount (amount: 0.095)
// macro_control_1 → env_2_attack (amount: 0.367)
// macro_control_3 → phaser_dry_wet (amount: 0.5)