// Vital Preset: E4 One Note Metallophone
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "e4_one_note_metallophone_osc1": ["e4_one_note_metallophone_osc1.wav"],
  "e4_one_note_metallophone_osc2": ["e4_one_note_metallophone_osc2.wav"],
  "e4_one_note_metallophone_osc3": ["e4_one_note_metallophone_osc3.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("e4_one_note_metallophone_osc1")
    .warp(0.5)
    .gain(0.497)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.904)
    // filter
    .cutoff(133)
    // modulation
    .lprate(0.5)
    .lpdepth(2968)
    .lpdc(0),
  note("c3 e3 g3 b3")
    .s("e4_one_note_metallophone_osc2")
    .warp(0.5)
    .gain(0.707)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.904)
    // filter
    .cutoff(133)
    // modulation
    .lprate(0.5)
    .lpdepth(2968)
    .lpdc(0),
  note("c3 e3 g3 b3")
    .s("e4_one_note_metallophone_osc3")
    .warp(0.5)
    .gain(0.422)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.904)
    // filter
    .cutoff(133)
    // modulation
    .lprate(0.5)
    .lpdepth(2968)
    .lpdc(0)
)

// === Unmapped modulations (Vital-specific) ===
// lfo_2 → osc_2_transpose (amount: 0.97)
// macro_control_1 → osc_2_level (amount: 0.65)
// macro_control_2 → sample_level (amount: 0.515)
// macro_control_3 → chorus_dry_wet (amount: 0.405)
// macro_control_3 → reverb_dry_wet (amount: 0.575)
// macro_control_4 → compressor_mix (amount: 1)
// macro_control_4 → volume (amount: -0.16)
// macro_control_4 → distortion_mix (amount: 1)