// Vital Preset: Easy Mallet
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
note("c3 e3 g3 b3")
  .s("sawtooth")
  // envelope
  .attack(0.397)
  .decay(1.31)
  .sustain(0.755)
  .release(0.904)
  // filter
  .cutoff(686)
  .resonance(4.28)
  // effects
  .room(0.45)
  .roomsize(0.91)
  .shape(0.05)

// === Unmapped modulations (Vital-specific) ===
// velocity → modulation_1_amount (amount: 0.259)
// velocity → env_1_attack (amount: -0.065)
// velocity → modulation_6_amount (amount: 0.1)
// velocity → modulation_3_amount (amount: 0.324)
// lfo_2 → modulation_9_amount (amount: 0.5)
// stereo → filter_2_cutoff (amount: 0.228)
// mod_wheel → modulation_5_amount (amount: 0.289)
// lfo_2 → modulation_13_amount (amount: 0.078)