// Vital Preset: Fleet
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "fleet_osc2": ["fleet_osc2.wav"],
  "fleet_osc3": ["fleet_osc3.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("triangle")
    .warpmode("bendm")
    .unison(2)
    .detune(3.558)
    .spread(0.8)
    .gain(0.812)
    // envelope
    .attack(0.329)
    .decay(1.185)
    .release(1.355)
    // filter
    .cutoff(81)
    // modulation (osc1)
    .warp(0.51)
    .warprate(0.5)
    .warpdepth(0.55)
    .warpshape("sine")
    .lpsync(4)
    .lpdepth(3912)
    .lpdc(0)
    .lpshape("sine")
    .room(sine.fast(32).range(0.074, 0.547))
    // effects
    .room(0.311)
    .roomsize(0.5),
  note("c3 e3 g3 b3")
    .s("fleet_osc2")
    .wt(0.754)
    .warpmode("pwm")
    .unison(16)
    .spread(0.8)
    .gain(0.556)
    // envelope
    .attack(0.329)
    .decay(1.185)
    .release(1.355)
    // filter
    .cutoff(81)
    // modulation (osc2)
    .warp(0.861)
    .warpsync(4)
    .warpdepth(0.469)
    .warpshape("sine")
    .detune(sine.fast(4).range(0.1, 5.991))
    .lpsync(4)
    .lpdepth(3912)
    .lpdc(0)
    .lpshape("sine")
    .room(sine.fast(32).range(0.074, 0.547))
    // effects
    .room(0.311)
    .roomsize(0.5),
  note("c3 e3 g3 b3")
    .s("fleet_osc3")
    .wt(0.221)
    .warp(0.5)
    .gain(0.707)
    // envelope
    .attack(0.329)
    .decay(1.185)
    .release(1.355)
    // filter
    .cutoff(81)
    // modulation
    .lpsync(4)
    .lpdepth(3912)
    .lpdc(0)
    .lpshape("sine")
    .room(sine.fast(32).range(0.074, 0.547))
    // effects
    .room(0.311)
    .roomsize(0.5)
)

// === Unmapped modulations (Vital-specific) ===
// lfo_2 → modulation_1_amount (amount: -0.447)
// lfo_3 → modulation_9_amount (amount: -0.499)
// lfo_6 → lfo_5_frequency (amount: 1)
// macro_control_1 → filter_2_mix (amount: -1)
// macro_control_1 → modulation_4_amount (amount: 0.242)
// macro_control_1 → modulation_6_amount (amount: -0.278)
// macro_control_2 → reverb_decay_time (amount: -0.532)
// random_1 → delay_filter_cutoff (amount: -1)