// Vital Preset: Float Chords
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "float_chords_osc2": ["float_chords_osc2.wav"],
  "float_chords_osc3": ["float_chords_osc3.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.435)
    .warpmode("sync")
    .unison(5)
    .detune(3.522)
    .spread(0.8)
    .gain(0.285)
    // envelope
    .attack(0.708)
    .decay(1)
    .release(1.285)
    // filter
    .cutoff(17)
    // modulation (osc1)
    .tremolosync(4)
    .tremolodepth(1)
    .tremoloshape("tri")
    .warpenv(0.08)
    .warpattack(0.708)
    .warpdecay(1)
    .warpsustain(1)
    .warprelease(1.285)
    .lpsync(4)
    .lpdepth(1827)
    .lpdc(0)
    // effects
    .room(0.385)
    .roomsize(0.73),
  note("c3 e3 g3 b3")
    .s("float_chords_osc2")
    .warp(0.5)
    .unison(5)
    .detune(2.622)
    .spread(0.8)
    // envelope
    .attack(0.708)
    .decay(1)
    .release(1.285)
    // filter
    .cutoff(17)
    // modulation (osc2)
    .tremolosync(4)
    .tremolodepth(1)
    .tremoloshape("tri")
    .wt(0.165)
    .wtsync(4)
    .wtdepth(0.627)
    .lpsync(4)
    .lpdepth(1827)
    .lpdc(0)
    // effects
    .room(0.385)
    .roomsize(0.73),
  note("c3 e3 g3 b3")
    .s("float_chords_osc3")
    .wt(0.482)
    .warp(0.5)
    .gain(0.15)
    // envelope
    .attack(0.708)
    .decay(1)
    .release(1.285)
    // filter
    .cutoff(17)
    // modulation (osc3)
    .tremolosync(4)
    .tremolodepth(0.98)
    .tremoloshape("tri")
    .lpsync(4)
    .lpdepth(1827)
    .lpdc(0)
    // effects
    .room(0.385)
    .roomsize(0.73)
)

// === Unmapped modulations (Vital-specific) ===
// macro_control_1 → delay_dry_wet (amount: 1)
// macro_control_1 → distortion_mix (amount: 1)
// macro_control_2 → sample_level (amount: 0.575)
// macro_control_3 → lfo_2_stereo (amount: 0.5)
// macro_control_4 → filter_1_cutoff (amount: 0.4)