// Vital Preset: FM Drum Circle
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "fm_drum_circle_osc1": ["fm_drum_circle_osc1.wav"],
})

// Pattern — change the notes to taste!
note("c3 e3 g3 b3")
  .s("fm_drum_circle_osc1")
  // envelope
  .attack(0.21)
  .decay(1)
  .release(0.548)
  // filter
  .cutoff(523)
  .ftype("24db")
  // effects
  .shape(0.333)

// === Unmapped modulations (Vital-specific) ===
// random_1 → osc_2_transpose (amount: 0.5)
// random_2 → osc_3_transpose (amount: 0.498)
// mod_wheel → random_2_tempo (amount: 0.167)
// mod_wheel → random_1_tempo (amount: 0.167)
// mod_wheel → lfo_1_tempo (amount: 0.167)
// macro_control_1 → modulation_2_amount (amount: 0.102)
// macro_control_1 → modulation_4_amount (amount: 0.071)
// macro_control_1 → distortion_filter_cutoff (amount: 0.285)