// Vital Preset: FM Mode
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "fm_mode_osc1": ["fm_mode_osc1.wav"],
})

// Pattern — change the notes to taste!
note("c3 e3 g3 b3")
  .s("fm_mode_osc1")
  .warp(0.095)
  .warpmode("asym")
  .gain(0.707)
  // envelope
  .attack(0.149)
  .decay(1)
  .release(0.999)
  // filter
  .cutoff(64)
  .resonance(2.381)
  // modulation
  .tremolosync(32)
  .tremolodepth(0.79)
  .tremoloshape("tri")
  .room(tri.fast(32).range(0.303, 0.837))
  .lpsync(32)
  .lpdepth(846)
  .lpdc(0)
  .resonance(tri.fast(32).range(1.837, 2.925))
  // effects
  .room(0.57)
  .roomsize(0.5)

// === Unmapped modulations (Vital-specific) ===
// lfo_1 → compressor_release (amount: -0.74)
// lfo_1 → distortion_drive (amount: 0.05)
// macro_control_1 → modulation_2_amount (amount: 0.178)
// velocity → modulation_3_amount (amount: 0.097)
// velocity → modulation_4_amount (amount: 0.077)
// note → filter_2_cutoff (amount: 0.62)
// note → filter_1_cutoff (amount: 0.701)
// macro_control_2 → filter_2_cutoff (amount: 0.72)