// Vital Preset: Fun Pulse
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
note("c3 e3 g3 b3")
  .s("sawtooth")
  .warp(0.54)
  .unison(5)
  .spread(0.8)
  .gain(0.775)
  // envelope
  .attack(0.149)
  .decay(1)
  // filter
  .cutoff(61)
  // modulation
  .wt(0.073)
  .wtsync(8)
  .wtdepth(0.927)
  .lpsync(64)
  .lpdepth(8149)
  .lpdc(0)

// === Unmapped modulations (Vital-specific) ===
// random_1 → osc_1_transpose (amount: 0.5)
// random_1 → filter_2_cutoff (amount: 0.334)
// macro_control_1 → distortion_mix (amount: 0.5)
// macro_control_2 → chorus_dry_wet (amount: 1)
// macro_control_3 → reverb_dry_wet (amount: 0.34)
// macro_control_3 → delay_dry_wet (amount: 0.392)
// random_1 → filter_fx_cutoff (amount: 0.094)
// macro_control_4 → filter_fx_mix (amount: 1)