// Vital Preset: Gorgled
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "gorgled_osc3": ["gorgled_osc3.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("triangle")
    .warp(0.5)
    .warpmode("bendm")
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.548)
    // filter
    .bandf(261)
    .bandq(15.586)
    // modulation (osc1)
    .wt(0)
    .wtsync(8)
    .wtdepth(1)
    .wtshape("sine")
    // effects
    .shape(0.169),
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.5)
    .unison(16)
    .detune(4.472)
    .spread(0.8)
    .gain(0.61)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.548)
    // filter
    .bandf(261)
    .bandq(15.586)
    // modulation (osc2)
    .wt(0.011)
    .wtsync(4)
    .wtdepth(0.571)
    .wtshape("sine")
    // effects
    .shape(0.169),
  note("c3 e3 g3 b3")
    .s("gorgled_osc3")
    .warp(0.218)
    .warpmode("asym")
    .gain(0.707)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.548)
    // filter
    .bandf(261)
    .bandq(15.586)
    // effects
    .shape(0.169)
)

// === Unmapped modulations (Vital-specific) ===
// lfo_1 → filter_1_blend_transpose (amount: 1)
// lfo_2 → filter_2_blend_transpose (amount: 1)
// lfo_6 → distortion_drive (amount: 0.234)
// macro_control_1 → filter_fx_mix (amount: 0.998)
// macro_control_1 → lfo_7_tempo (amount: 0.042)
// macro_control_2 → osc_2_level (amount: 0.39)
// macro_control_2 → osc_1_level (amount: -0.96)
// macro_control_2 → chorus_dry_wet (amount: 1)