// Vital Preset: Growl Bass Sidechain
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "growl_bass_sidechain_osc2": ["growl_bass_sidechain_osc2.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.5)
    .gain(0.497)
    // envelope
    .attack(0.257)
    .decay(0.834)
    .release(0.488)
    // filter
    .cutoff(10786)
    .resonance(1.368)
    // modulation (osc1)
    .tremolosync(32)
    .tremolodepth(0.293)
    .tremoloshape("tri"),
  note("c3 e3 g3 b3")
    .s("growl_bass_sidechain_osc2")
    .wt(0.411)
    .warp(0.5)
    .unison(12)
    .detune(2.9)
    .spread(0.8)
    .gain(0.517)
    // envelope
    .attack(0.257)
    .decay(0.834)
    .release(0.488)
    // filter
    .cutoff(10786)
    .resonance(1.368)
    // modulation (osc2)
    .tremolosync(32)
    .tremolodepth(0.413)
    .tremoloshape("tri")
)

// === Unmapped modulations (Vital-specific) ===
// macro_control_4 → chorus_dry_wet (amount: 1)
// macro_control_3 → reverb_dry_wet (amount: 0.36)
// macro_control_1 → eq_low_gain (amount: 0.105)
// macro_control_2 → filter_fx_cutoff (amount: 1)
// macro_control_4 → osc_2_spectral_morph_amount (amount: 0.135)
// macro_control_1 → distortion_mix (amount: 0.27)
// random_1 → osc_1_spectral_morph_amount (amount: 0.14)