// Vital Preset: Honk Wub
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "honk_wub_osc2": ["honk_wub_osc2.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("square")
    .warp(0.5)
    .warpmode("pwm")
    .gain(0.707)
    // envelope
    .decay(1)
    .release(0.405)
    // filter
    .cutoff(4658)
    .resonance(20)
    .ftype("24db")
    // modulation (osc1)
    .wt(0.135)
    .wtsync(16)
    .wtdepth(0.378)
    .tremolosync(32)
    .tremolodepth(0.995)
    .tremoloshape("tri")
    .lpsync(32)
    .lpdepth(16437)
    .lpdc(0)
    // effects
    .delay(0.18)
    .delaytime(1)
    .delayfeedback(0.26),
  note("c3 e3 g3 b3")
    .s("honk_wub_osc2")
    .warp(0.5)
    .warpmode("pwm")
    .gain(0.475)
    // envelope
    .decay(1)
    .release(0.405)
    // filter
    .cutoff(4658)
    .resonance(20)
    .ftype("24db")
    // modulation (osc2)
    .tremolosync(32)
    .tremolodepth(0.89)
    .tremoloshape("tri")
    .warpenv(0.51)
    .warpattack(0.583)
    .warpdecay(0.924)
    .warprelease(0.548)
    .lpsync(32)
    .lpdepth(16437)
    .lpdc(0)
    // effects
    .delay(0.18)
    .delaytime(1)
    .delayfeedback(0.26),
  note("c3 e3 g3 b3")
    .s("square")
    .warp(0.5)
    .warpmode("pwm")
    .gain(0.707)
    // envelope
    .decay(1)
    .release(0.405)
    // filter
    .cutoff(4658)
    .resonance(20)
    .ftype("24db")
    // modulation (osc3)
    .tremolosync(32)
    .tremolodepth(1)
    .tremoloshape("tri")
    .wt(0.378)
    .wtsync(16)
    .wtdepth(0.86)
    .warpenv(0.24)
    .warpattack(0.149)
    .warpdecay(1.232)
    .warprelease(1.19)
    .lpsync(32)
    .lpdepth(16437)
    .lpdc(0)
    // effects
    .delay(0.18)
    .delaytime(1)
    .delayfeedback(0.26)
)

// === Unmapped modulations (Vital-specific) ===
// lfo_3 → filter_1_blend_transpose (amount: 0.415)
// lfo_2 → filter_1_formant_y (amount: 0.99)
// lfo_5 → filter_1_formant_x (amount: 0.54)
// lfo_5 → filter_1_formant_spread (amount: -0.57)
// env_4 → filter_fx_drive (amount: 0.99)
// lfo_2 → distortion_drive (amount: 0.985)
// lfo_2 → compressor_band_gain (amount: 0.18)
// macro_control_1 → reverb_dry_wet (amount: 0.995)