// Vital Preset: Horror of Melbourne 1
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "horror_of_melbourne_1_osc1": ["horror_of_melbourne_1_osc1.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("horror_of_melbourne_1_osc1")
    .gain(0.707)
    // envelope
    .attack(0.34)
    .decay(1)
    .release(0.512)
    // filter
    .cutoff(101)
    .resonance(20)
    // effects
    .room(0.445)
    .roomsize(0.5),
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .gain(0.707)
    // envelope
    .attack(0.34)
    .decay(1)
    .release(0.512)
    // filter
    .cutoff(101)
    .resonance(20)
    // effects
    .room(0.445)
    .roomsize(0.5)
)

// === Unmapped modulations (Vital-specific) ===
// macro_control_1 → distortion_filter_resonance (amount: 0.06)
// macro_control_2 → distortion_mix (amount: 1)
// env_1 → reverb_dry_wet (amount: -0.95)
// macro_control_3 → filter_1_cutoff (amount: 0.768)
// macro_control_1 → filter_2_cutoff (amount: 0.595)
// mod_wheel → osc_2_level (amount: 0.77)
// mod_wheel → osc_1_level (amount: -1)
// macro_control_4 → modulation_10_amount (amount: 0.5)