// Vital Preset: Jupiter Bass
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "jupiter_bass_osc2": ["jupiter_bass_osc2.wav"],
  "jupiter_bass_osc3": ["jupiter_bass_osc3.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("jupiter_bass_osc2")
    .warp(0.5)
    .gain(0.294)
    // envelope
    .attack(0.4)
    .decay(1)
    .release(0.643)
    // filter
    .cutoff(858)
    .resonance(14.331)
    .ftype("ladder")
    // effects
    .room(0.118)
    .roomsize(0.5),
  note("c3 e3 g3 b3")
    .s("jupiter_bass_osc3")
    .wt(0.837)
    .warp(0.5)
    .gain(0.441)
    // envelope
    .attack(0.4)
    .decay(1)
    .release(0.643)
    // filter
    .cutoff(858)
    .resonance(14.331)
    .ftype("ladder")
    // effects
    .room(0.118)
    .roomsize(0.5)
)

// === Unmapped modulations (Vital-specific) ===
// env_2 → filter_1_resonance (amount: 0.112)
// macro_control_2 → sample_level (amount: 0.124)
// macro_control_3 → osc_2_unison_voices (amount: 0.22)
// macro_control_4 → modulation_6_amount (amount: 0.018)
// macro_control_4 → modulation_7_amount (amount: 0.09)
// macro_control_4 → modulation_8_amount (amount: 0.012)
// macro_control_4 → modulation_9_amount (amount: -0.024)
// mod_wheel → env_2_sustain (amount: 0.994)