// Vital Preset: Keystation
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "keystation_osc1": ["keystation_osc1.wav"],
  "keystation_osc2": ["keystation_osc2.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("keystation_osc1")
    .warp(0.755)
    .warpmode("bendm")
    .unison(3)
    .detune(2.363)
    .gain(0.211)
    // envelope
    .attack(0.347)
    .decay(1)
    .release(1.379)
    // filter
    .cutoff(261)
    .resonance(1.216)
    .ftype("24db")
    // effects
    .room(0.25)
    .roomsize(0.5),
  note("c3 e3 g3 b3")
    .s("keystation_osc2")
    .gain(0.15)
    // envelope
    .attack(0.347)
    .decay(1)
    .release(1.379)
    // filter
    .cutoff(261)
    .resonance(1.216)
    .ftype("24db")
    // effects
    .room(0.25)
    .roomsize(0.5)
)

// === Unmapped modulations (Vital-specific) ===
// velocity → modulation_1_amount (amount: 0.086)
// velocity → osc_1_level (amount: 0.438)
// note → osc_1_distortion_amount (amount: 1)
// velocity → env_1_attack (amount: -0.06)
// velocity → osc_2_level (amount: 0.258)
// velocity → modulation_7_amount (amount: 0.181)
// note → env_2_decay (amount: -0.525)
// macro_control_4 → reverb_decay_time (amount: 0.219)