// Vital Preset: Kick Drum 1
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "kick_drum_1_osc1": ["kick_drum_1_osc1.wav"],
})

// Pattern — change the notes to taste!
note("c3 e3 g3 b3")
  .s("kick_drum_1_osc1")
  .warp(0.5)
  .gain(0.707)
  // envelope
  .decay(0.608)
  .sustain(0)
  .release(0.334)
  // modulation
  .tremolosync(16)
  .tremolodepth(1)

// === Unmapped modulations (Vital-specific) ===
// lfo_1 → osc_1_transpose (amount: 0.63)
// lfo_3 → distortion_drive (amount: 0.245)