// Vital Preset: LORN Style Lead
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "lorn_style_lead_osc1": ["lorn_style_lead_osc1.wav"],
})

// Pattern — change the notes to taste!
note("c3 e3 g3 b3")
  .s("lorn_style_lead_osc1")
  .wt(0.285)
  .warp(0.5)
  .gain(0.707)
  // envelope
  .attack(0.149)
  .decay(1.027)
  // filter
  .cutoff(57)
  .resonance(13.464)
  // modulation
  .tremolo(0.5)
  .tremolodepth(0.995)
  .tremoloshape("tri")
  .lpsync(1)
  .lpdepth(18000)
  .lpdc(0)

// === Unmapped modulations (Vital-specific) ===
// lfo_1 → osc_1_transpose (amount: 0.5)
// lfo_1 → compressor_high_gain (amount: 0.25)
// lfo_1 → filter_fx_formant_transpose (amount: 0.858)
// macro_control_1 → chorus_dry_wet (amount: 0.87)
// lfo_3 → lfo_2_tempo (amount: 0.333)
// lfo_3 → lfo_2_frequency (amount: 0.9)
// macro_control_2 → distortion_drive (amount: 0.11)
// macro_control_2 → distortion_mix (amount: 1)