// Vital Preset: Memory Leak
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "memory_leak_osc1": ["memory_leak_osc1.wav"],
  "memory_leak_osc2": ["memory_leak_osc2.wav"],
  "memory_leak_osc3": ["memory_leak_osc3.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("memory_leak_osc1")
    .wt(0.478)
    .warpmode("sync")
    .unison(2)
    .detune(2.522)
    .spread(0.8)
    .gain(0.707)
    // envelope
    .attack(0.601)
    .decay(1)
    .release(0.714)
    // modulation (osc1)
    .warp(0.5)
    .warpsync(16)
    .warpdepth(0.32)
    .warpshape("sine")
    // effects
    .delay(1)
    .delaytime(0.111)
    .delayfeedback(0.03)
    .shape(0.26)
    .coarse(4),
  note("c3 e3 g3 b3")
    .s("memory_leak_osc2")
    .warp(0.5)
    .pan(0.375)
    .gain(0.707)
    // envelope
    .attack(0.601)
    .decay(1)
    .release(0.714)
    // effects
    .delay(1)
    .delaytime(0.111)
    .delayfeedback(0.03)
    .shape(0.26)
    .coarse(4),
  note("c3 e3 g3 b3")
    .s("memory_leak_osc3")
    .wt(0.471)
    .warp(0.5)
    .pan(0.62)
    .gain(0.707)
    // envelope
    .attack(0.601)
    .decay(1)
    .release(0.714)
    // effects
    .delay(1)
    .delaytime(0.111)
    .delayfeedback(0.03)
    .shape(0.26)
    .coarse(4)
)

// === Unmapped modulations (Vital-specific) ===
// macro_control_1 → osc_1_distortion_amount (amount: 0.2)
// macro_control_3 → sample_level (amount: 1)
// lfo_2 → voice_transpose (amount: 0.5)
// random_1 → osc_1_wave_frame (amount: -0.35)
// macro_control_2 → modulation_3_amount (amount: 0.18)
// macro_control_2 → osc_1_wave_frame (amount: -0.278)
// macro_control_3 → delay_feedback (amount: 0.315)
// macro_control_3 → delay_aux_frequency (amount: -0.07)