// Vital Preset: Metal Head
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "metal_head_osc2": ["metal_head_osc2.wav"],
  "metal_head_osc3": ["metal_head_osc3.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("metal_head_osc2")
    .warp(0.5)
    .unison(16)
    .detune(10)
    .spread(0.8)
    .gain(0.15)
    // envelope
    .attack(0.345)
    .decay(1)
    .release(1.321)
    // filter
    .cutoff(261)
    // effects
    .room(0.42)
    .roomsize(0.1)
    .delay(0.161)
    .delaytime(0.667)
    .delayfeedback(0.57)
    .shape(0.229),
  note("c3 e3 g3 b3")
    .s("metal_head_osc3")
    .warp(0.5)
    .unison(8)
    .detune(10)
    .spread(0.675)
    .gain(0.15)
    // envelope
    .attack(0.345)
    .decay(1)
    .release(1.321)
    // filter
    .cutoff(261)
    // effects
    .room(0.42)
    .roomsize(0.1)
    .delay(0.161)
    .delaytime(0.667)
    .delayfeedback(0.57)
    .shape(0.229)
)

// === Unmapped modulations (Vital-specific) ===
// velocity → modulation_2_amount (amount: 0.5)
// stereo → osc_1_detune_range (amount: 0.719)
// stereo → osc_1_unison_detune (amount: 0.207)
// stereo → osc_1_spectral_morph_amount (amount: 0.109)
// stereo → env_2_release (amount: -0.123)
// stereo → env_2_decay (amount: 0.107)
// stereo → env_2_hold (amount: 0.38)
// stereo → osc_1_distortion_amount (amount: -0.133)