// Vital Preset: Moog Pluck
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "moog_pluck_osc1": ["moog_pluck_osc1.wav"],
  "moog_pluck_osc2": ["moog_pluck_osc2.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("moog_pluck_osc1")
    .wt(0.411)
    .warp(0.5)
    .gain(0.772)
    // envelope
    .attack(0.369)
    .decay(1.187)
    .sustain(0.558)
    .release(0.571)
    // filter
    .cutoff(29)
    .ftype("24db")
    .lpenv(8.727)
    .lpdecay(1.023)
    .lpsustain(0.232)
    .lprelease(0.548),
  note("c3 e3 g3 b3")
    .s("moog_pluck_osc2")
    .wt(0.403)
    .warp(0.73)
    .warpmode("bendm")
    .unison(5)
    .detune(3.1)
    .spread(0.8)
    .gain(0.27)
    // envelope
    .attack(0.369)
    .decay(1.187)
    .sustain(0.558)
    .release(0.571)
    // filter
    .cutoff(29)
    .ftype("24db")
    .lpenv(8.727)
    .lpdecay(1.023)
    .lpsustain(0.232)
    .lprelease(0.548)
)

// === Unmapped modulations (Vital-specific) ===
// macro_control_1 → reverb_dry_wet (amount: 0.27)
// macro_control_2 → env_1_attack (amount: 0.14)
// macro_control_3 → filter_fx_cutoff (amount: 1)