// Vital Preset: Moving Harmonics
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "moving_harmonics_osc2": ["moving_harmonics_osc2.wav"],
  "moving_harmonics_osc3": ["moving_harmonics_osc3.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .unison(3)
    .spread(0.8)
    .gain(0.707)
    // envelope
    .attack(0.149)
    .decay(0.929)
    .release(0.321)
    // filter
    .cutoff(455)
    // modulation (osc1)
    .warp(0.5)
    .warpsync(4)
    .warpdepth(1),
  note("c3 e3 g3 b3")
    .s("moving_harmonics_osc2")
    .wt(0.01)
    .warp(0.5)
    // envelope
    .attack(0.149)
    .decay(0.929)
    .release(0.321)
    // filter
    .cutoff(455),
  note("c3 e3 g3 b3")
    .s("moving_harmonics_osc3")
    .warp(0.5)
    .unison(6)
    .detune(3.2)
    .spread(0.8)
    .gain(0.49)
    // envelope
    .attack(0.149)
    .decay(0.929)
    .release(0.321)
    // filter
    .cutoff(455)
)

// === Unmapped modulations (Vital-specific) ===
// macro_control_1 → filter_2_mix (amount: 1)
// macro_control_2 → delay_dry_wet (amount: 0.277)
// macro_control_2 → reverb_dry_wet (amount: 0.405)
// macro_control_3 → distortion_mix (amount: 0.5)
// macro_control_1 → eq_high_gain (amount: -0.195)
// mod_wheel → filter_fx_cutoff (amount: 0.996)
// env_1 → modulation_9_amount (amount: 0.235)