// Vital Preset: Phaser Man
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
note("c3 e3 g3 b3")
  .s("triangle")
  .warpmode("bendm")
  .gain(0.707)
  // envelope
  .attack(0.071)
  .decay(1)
  .release(0.238)
  // filter
  .cutoff(54)
  // modulation
  .warp(1)
  .warpsync(16)
  .warpdepth(0.58)
  .lpsync(16)
  .lpdepth(6139)
  .lpdc(0)
  // effects
  .shape(0.3)

// === Unmapped modulations (Vital-specific) ===
// lfo_2 → osc_1_distortion_phase (amount: 1)
// macro_control_4 → reverb_dry_wet (amount: 0.6)
// lfo_5 → phaser_center (amount: -0.32)
// macro_control_3 → phaser_dry_wet (amount: 1)
// velocity → modulation_1_amount (amount: 0.5)
// macro_control_1 → lfo_2_tempo (amount: 0.13)
// macro_control_1 → lfo_1_tempo (amount: -0.143)
// macro_control_1 → lfo_3_tempo (amount: 0.087)