// Vital Preset: Phaser Entropy 
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
note("c3 e3 g3 b3")
  .s("sawtooth")
  .warpmode("fold")
  .unison(7)
  .spread(1)
  .gain(0.707)
  // envelope
  .attack(0.149)
  .decay(1)
  // filter
  .cutoff(216)
  .resonance(13.412)
  // modulation
  .wt(0)
  .wtsync(8)
  .wtdepth(1)
  .tremolosync(8)
  .tremolodepth(0.84)
  .tremoloshape("tri")
  .warp(0.5)
  .warpsync(8)
  .warpdepth(0.05)
  .lpsync(8)
  .lpdepth(1942)
  .lpdc(0)
  .resonance(tri.fast(8).range(6.017, 20))

// === Unmapped modulations (Vital-specific) ===
// env_1 → chorus_dry_wet (amount: 0.54)
// macro_control_1 → filter_fx_cutoff (amount: 0.619)
// lfo_2 → phaser_center (amount: -0.46)
// lfo_2 → phaser_mod_depth (amount: -0.66)
// lfo_2 → phaser_phase_offset (amount: -0.422)
// lfo_2 → phaser_blend (amount: -1)
// lfo_2 → phaser_feedback (amount: 0.28)
// macro_control_1 → filter_1_cutoff (amount: 0.232)