// Vital Preset: Physical Tension
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
note("c3 e3 g3 b3")
  .s("sawtooth")
  .warp(0.5)
  .gain(0.707)
  // envelope
  .decay(0.274)
  .sustain(0)
  // filter
  .cutoff(54)
  .resonance(10.504)

// === Unmapped modulations (Vital-specific) ===
// macro_control_4 → reverb_dry_wet (amount: 1)
// macro_control_1 → chorus_delay_2 (amount: -0.99)
// macro_control_1 → chorus_delay_1 (amount: -1)
// macro_control_2 → modulation_1_amount (amount: 0.25)
// note → osc_1_transpose (amount: 1)
// macro_control_3 → chorus_cutoff (amount: 1)
// mod_wheel → chorus_feedback (amount: 1)
// velocity → osc_1_level (amount: 1)