// Vital Preset: Piano from the yard sale
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "piano_from_the_yard_sale_osc1": ["piano_from_the_yard_sale_osc1.wav"],
  "piano_from_the_yard_sale_osc3": ["piano_from_the_yard_sale_osc3.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("piano_from_the_yard_sale_osc1")
    .warp(0.5)
    .unison(2)
    .detune(10)
    .spread(1)
    .gain(0.707)
    // envelope
    .decay(1.274)
    .sustain(0)
    .release(1.011)
    // filter
    .cutoff(261)
    .resonance(4.632)
    .ftype("ladder"),
  note("c3 e3 g3 b3")
    .s("piano_from_the_yard_sale_osc3")
    .warp(0.5)
    .gain(0.707)
    // envelope
    .decay(1.274)
    .sustain(0)
    .release(1.011)
    // filter
    .cutoff(261)
    .resonance(4.632)
    .ftype("ladder")
)

// === Unmapped modulations (Vital-specific) ===
// env_2 → osc_1_detune_power (amount: -0.81)
// env_2 → osc_1_spectral_morph_spread (amount: 0.38)
// env_2 → osc_1_frame_spread (amount: 0.26)
// env_2 → osc_1_transpose (amount: 0.5)
// env_2 → osc_1_level (amount: 0.773)
// env_3 → filter_2_blend_transpose (amount: 0.065)
// env_3 → filter_2_blend (amount: 0.118)
// note → osc_2_transpose (amount: -0.13)