// Vital Preset: Plucked String
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
note("c3 e3 g3 b3")
  .s("sawtooth")
  // envelope
  .attack(0.115)
  .decay(0.936)
  .release(0.809)
  // filter
  .bandf(261)
  .bandq(19.8)
  // effects
  .room(0.394)
  .roomsize(0.5)
  .shape(0.397)

// === Unmapped modulations (Vital-specific) ===
// env_2 → sample_level (amount: 1)
// velocity → filter_2_cutoff (amount: 0.367)
// macro_control_1 → modulation_3_amount (amount: 0.377)
// macro_control_2 → filter_1_blend (amount: 1)
// macro_control_3 → reverb_decay_time (amount: 0.691)
// macro_control_1 → filter_1_blend_transpose (amount: 0.16)