// Vital Preset: Railgun
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.5)
    .gain(0.707)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.548)
    // filter
    .cutoff(21096)
    .resonance(9.925)
    // modulation (osc1)
    .wtenv(1)
    .wtattack(0.166)
    .wtdecay(0.859)
    .warpenv(1)
    .warpattack(0.166)
    .warpdecay(0.859)
    // effects
    .room(0.065)
    .roomsize(0.5),
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.5)
    .gain(0.707)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.548)
    // filter
    .cutoff(21096)
    .resonance(9.925)
    // modulation (osc2)
    .tremolosync(16)
    .tremolodepth(1)
    .tremoloshape("tri")
    .wtenv(1)
    .wtattack(0.166)
    .wtdecay(0.859)
    .warpenv(1)
    .warpattack(0.166)
    .warpdecay(0.859)
    // effects
    .room(0.065)
    .roomsize(0.5)
)

// === Unmapped modulations (Vital-specific) ===
// env_2 → osc_1_unison_voices (amount: 1)
// env_2 → filter_1_drive (amount: 0.25)
// env_2 → osc_1_transpose (amount: 0.21)
// env_2 → distortion_drive (amount: 0.29)
// env_2 → osc_2_transpose (amount: 0.225)
// env_2 → flanger_center (amount: 1)
// lfo_3 → osc_1_transpose (amount: -0.165)
// lfo_3 → osc_2_transpose (amount: -0.17)