// Vital Preset: Random Amp Growl
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "random_amp_growl_osc3": ["random_amp_growl_osc3.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("triangle")
    .warp(0.765)
    .warpmode("bendm")
    .gain(0.707)
    // envelope
    .attack(0.654)
    .decay(1)
    .release(0.58)
    // filter
    .cutoff(135)
    .resonance(13.204)
    // effects
    .shape(0.11),
  note("c3 e3 g3 b3")
    .s("triangle")
    .warp(0.185)
    .warpmode("bendmp")
    .gain(0.707)
    // envelope
    .attack(0.654)
    .decay(1)
    .release(0.58)
    // filter
    .cutoff(135)
    .resonance(13.204)
    // effects
    .shape(0.11),
  note("c3 e3 g3 b3")
    .s("random_amp_growl_osc3")
    .warp(0.5)
    .gain(0.707)
    // envelope
    .attack(0.654)
    .decay(1)
    .release(0.58)
    // filter
    .cutoff(135)
    .resonance(13.204)
    // effects
    .shape(0.11)
)

// === Unmapped modulations (Vital-specific) ===
// macro_control_1 → osc_1_wave_frame (amount: 0.35)
// macro_control_1 → osc_3_level (amount: 0.912)
// macro_control_1 → osc_1_distortion_amount (amount: -0.23)
// macro_control_1 → osc_1_level (amount: 0.533)
// macro_control_1 → osc_2_wave_frame (amount: 0.543)
// macro_control_1 → osc_2_distortion_amount (amount: 0.225)
// macro_control_2 → osc_1_spectral_morph_amount (amount: 1)
// macro_control_1 → filter_1_cutoff (amount: 0.154)