// Vital Preset: Real Squarepusher Hours
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "real_squarepusher_hours_osc3": ["real_squarepusher_hours_osc3.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.72)
    .unison(3)
    .detune(1.022)
    .spread(0.8)
    .gain(0.497)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.179)
    // filter
    .cutoff(606)
    .resonance(5.49)
    // modulation (osc1)
    .wt(0.176)
    .wtsync(2)
    .wtdepth(0.724)
    // effects
    .room(0.59)
    .roomsize(0.5)
    .shape(0.19),
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.5)
    .gain(0.707)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.179)
    // filter
    .cutoff(606)
    .resonance(5.49)
    // modulation (osc2)
    .tremolosync(2)
    .tremolodepth(0.395)
    .tremoloshape("tri")
    // effects
    .room(0.59)
    .roomsize(0.5)
    .shape(0.19),
  note("c3 e3 g3 b3")
    .s("real_squarepusher_hours_osc3")
    .warp(0.5)
    .unison(3)
    .detune(1.822)
    .spread(0.8)
    .gain(0.757)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.179)
    // filter
    .cutoff(606)
    .resonance(5.49)
    // effects
    .room(0.59)
    .roomsize(0.5)
    .shape(0.19)
)

// === Unmapped modulations (Vital-specific) ===
// lfo_1 → osc_1_transpose (amount: 0.5)
// lfo_2 → osc_3_transpose (amount: 0.5)
// lfo_3 → osc_2_transpose (amount: 0.5)
// lfo_5 → osc_1_transpose (amount: 0.5)
// macro_control_1 → osc_1_transpose (amount: 0.5)
// macro_control_2 → filter_1_cutoff (amount: 0.48)
// macro_control_3 → filter_1_drive (amount: 1)
// macro_control_3 → distortion_drive (amount: 0.115)