// Vital Preset: Remedial Shikari
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "remedial_shikari_osc1": ["remedial_shikari_osc1.wav"],
  "remedial_shikari_osc2": ["remedial_shikari_osc2.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("remedial_shikari_osc1")
    .wt(0.079)
    .warp(0.3)
    .warpmode("sync")
    .gain(0.15)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.548)
    // modulation (osc1)
    .tremolosync(1)
    .tremolodepth(0.96)
    .tremoloshape("tri")
    // effects
    .delay(0.373)
    .delaytime(0.333)
    .delayfeedback(0.5)
    .shape(0.25),
  note("c3 e3 g3 b3")
    .s("remedial_shikari_osc2")
    .wt(0.197)
    .warp(0.5)
    .warpmode("sync")
    .gain(0.15)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.548)
    // modulation (osc2)
    .tremolosync(1)
    .tremolodepth(1)
    .tremoloshape("tri")
    // effects
    .delay(0.373)
    .delaytime(0.333)
    .delayfeedback(0.5)
    .shape(0.25)
)

// === Unmapped modulations (Vital-specific) ===
// random_1 → osc_1_spectral_morph_amount (amount: -0.3)
// random_1 → osc_1_distortion_amount (amount: 0.505)
// lfo_1 → osc_1_unison_voices (amount: 1)
// macro_control_1 → osc_1_spectral_morph_amount (amount: 0.05)
// macro_control_1 → osc_1_distortion_amount (amount: 0.13)
// lfo_3 → osc_2_transpose (amount: 0.75)
// macro_control_3 → distortion_drive (amount: 0.145)
// macro_control_2 → osc_2_spectral_morph_amount (amount: 0.5)