// Vital Preset: Salomon
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "salomon_osc2": ["salomon_osc2.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("triangle")
    .unison(16)
    .detune(2.25)
    .gain(0.707)
    // envelope
    .attack(0.934)
    .decay(1)
    .sustain(0.735)
    .release(1.166)
    // filter
    .cutoff(1569)
    .resonance(17.143)
    // modulation (osc1)
    .wt(0.243)
    .wtrate(0.5)
    .wtdepth(0.348)
    .wtshape("sine")
    .pan(sine.fast(12).range(0.355, 0.645))
    // effects
    .room(0.38)
    .roomsize(0.5)
    .delay(0.093)
    .delaytime(0.333)
    .delayfeedback(0.5)
    .shape(0.06),
  note("c3 e3 g3 b3")
    .s("salomon_osc2")
    .warpmode("bendm")
    .unison(8)
    .detune(3.122)
    .spread(0.31)
    .gain(0.382)
    // envelope
    .attack(0.934)
    .decay(1)
    .sustain(0.735)
    .release(1.166)
    // filter
    .cutoff(1569)
    .resonance(17.143)
    // modulation (osc2)
    .warp(0.5)
    .warprate(0.5)
    .warpdepth(0.14)
    .warpshape("sine")
    .wt(0)
    .wtrate(0.5)
    .wtdepth(1)
    .wtshape("sine")
    .pan(sine.fast(12).range(0.355, 0.645))
    // effects
    .room(0.38)
    .roomsize(0.5)
    .delay(0.093)
    .delaytime(0.333)
    .delayfeedback(0.5)
    .shape(0.06),
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.32)
    .warpmode("sync")
    .pan(0.52)
    .gain(0.325)
    // envelope
    .attack(0.934)
    .decay(1)
    .sustain(0.735)
    .release(1.166)
    // filter
    .cutoff(1569)
    .resonance(17.143)
    // modulation
    .pan(sine.fast(12).range(0.355, 0.645))
    // effects
    .room(0.38)
    .roomsize(0.5)
    .delay(0.093)
    .delaytime(0.333)
    .delayfeedback(0.5)
    .shape(0.06)
)

// === Unmapped modulations (Vital-specific) ===
// random_1 → osc_1_spectral_morph_amount (amount: 0.49)
// lfo_3 → osc_3_transpose (amount: -0.44)
// random_1 → modulation_4_amount (amount: 0.242)
// random_1 → modulation_2_amount (amount: 0.252)
// random → osc_1_pan (amount: 0.29)
// random_1 → osc_1_pan (amount: 0.21)
// lfo_5 → sample_transpose (amount: -0.49)
// velocity → filter_1_mix (amount: 1)