// Vital Preset: Satellites
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "satellites_osc1": ["satellites_osc1.wav"],
  "satellites_osc2": ["satellites_osc2.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("satellites_osc1")
    .warp(0.5)
    .unison(4)
    .detune(4.472)
    .spread(0.8)
    .gain(0.165)
    // envelope
    .attack(0.673)
    .decay(1)
    .sustain(0.52)
    .release(0.845)
    // filter
    .cutoff(2407)
    .ftype("24db")
    // effects
    .room(0.13)
    .roomsize(0.335)
    .delay(0.173)
    .delaytime(0.5)
    .delayfeedback(0.62)
    .shape(0.03),
  note("c3 e3 g3 b3")
    .s("satellites_osc2")
    .gain(0.707)
    // envelope
    .attack(0.673)
    .decay(1)
    .sustain(0.52)
    .release(0.845)
    // filter
    .cutoff(2407)
    .ftype("24db")
    // modulation (osc2)
    .warpenv(0.3)
    .warpattack(0.625)
    .warpdecay(1)
    .warpsustain(1)
    .warprelease(1.165)
    // effects
    .room(0.13)
    .roomsize(0.335)
    .delay(0.173)
    .delaytime(0.5)
    .delayfeedback(0.62)
    .shape(0.03),
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.5)
    .gain(0.707)
    // envelope
    .attack(0.673)
    .decay(1)
    .sustain(0.52)
    .release(0.845)
    // filter
    .cutoff(2407)
    .ftype("24db")
    // effects
    .room(0.13)
    .roomsize(0.335)
    .delay(0.173)
    .delaytime(0.5)
    .delayfeedback(0.62)
    .shape(0.03)
)

// === Unmapped modulations (Vital-specific) ===
// random → osc_1_spectral_morph_amount (amount: 0.3)
// random → osc_1_tune (amount: -0.12)
// random → env_1_sustain (amount: 0.1)
// random → osc_2_level (amount: 0.173)
// random_1 → osc_1_tune (amount: 0.14)
// random_1 → osc_2_tune (amount: -0.2)
// velocity → osc_1_level (amount: 0.73)
// velocity → osc_2_level (amount: 0.89)