// Vital Preset: Shepard Tone Template
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "shepard_tone_template_osc1": ["shepard_tone_template_osc1.wav"],
})

// Pattern — change the notes to taste!
note("c3 e3 g3 b3")
  .s("shepard_tone_template_osc1")
  .unison(10)
  .detune(3.097)
  .spread(0.8)
  .gain(0.707)
  // envelope
  .attack(0.149)
  .decay(1)
  .release(0.548)
  // modulation
  .warp(0.5)
  .warpsync(1)
  .warpdepth(1)