// Vital Preset: Simple Weoum
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.5)
    .gain(0.707)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.548)
    // modulation (osc1)
    .wt(0.216)
    .wtsync(32)
    .wtdepth(0.19)
    .tremolo(1)
    .tremolodepth(1)
    .tremoloshape("tri")
    .lprate(1)
    .lpdepth(3828)
    .lpdc(0)
    // effects
    .delay(0.233)
    .delaytime(0.292)
    .delayfeedback(0.26)
    .shape(0.19),
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.5)
    .gain(0.707)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.548)
    // modulation (osc2)
    .tremolo(1)
    .tremolodepth(1)
    .tremoloshape("tri")
    .lprate(1)
    .lpdepth(3828)
    .lpdc(0)
    // effects
    .delay(0.233)
    .delaytime(0.292)
    .delayfeedback(0.26)
    .shape(0.19),
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.5)
    .gain(0.707)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.548)
    // modulation (osc3)
    .tremolo(1)
    .tremolodepth(1)
    .tremoloshape("tri")
    .lprate(1)
    .lpdepth(3828)
    .lpdc(0)
    // effects
    .delay(0.233)
    .delaytime(0.292)
    .delayfeedback(0.26)
    .shape(0.19)
)

// === Unmapped modulations (Vital-specific) ===
// lfo_1 → flanger_center (amount: -0.188)
// lfo_1 → phaser_center (amount: -0.092)
// macro_control_1 → flanger_center (amount: 0.202)
// macro_control_2 → phaser_center (amount: 0.352)
// macro_control_3 → delay_frequency (amount: 0.167)
// mod_wheel → lfo_2_frequency (amount: 0.16)