// Vital Preset: Skew Resandal
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
note("c3 e3 g3 b3")
  .s("triangle")
  .warpmode("bendmp")
  .gain(0.707)
  // envelope
  .attack(0.149)
  .decay(1)
  .release(0.298)
  // filter
  .cutoff(16)
  .resonance(4.493)
  .lpenv(11.333)
  .lpdecay(1.071)
  .lprelease(0.655)
  // modulation
  .wt(0)
  .wtsync(8)
  .wtdepth(1)
  .warp(1)
  .warpsync(8)
  .warpdepth(1)

// === Unmapped modulations (Vital-specific) ===
// macro_control_1 → osc_1_spectral_morph_amount (amount: 1)
// macro_control_2 → lfo_1_tempo (amount: 0.25)
// macro_control_2 → lfo_2_tempo (amount: 0.25)
// macro_control_3 → modulation_6_amount (amount: 0.5)
// mod_wheel → env_2_sustain (amount: 1)
// velocity → modulation_9_amount (amount: 0.5)
// mod_wheel → delay_dry_wet (amount: 0.732)
// macro_control_4 → delay_dry_wet (amount: 0.352)