// Vital Preset: Smoker's Lounge
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.5)
    .unison(7)
    .detune(3.622)
    .spread(0.8)
    .gain(0.762)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.976)
    // filter
    .cutoff(46)
    .resonance(2.857)
    // modulation (osc1)
    .wt(0.394)
    .wtsync(16)
    .wtdepth(0.106)
    .lpsync(16)
    .lpdepth(1365)
    .lpdc(0)
    .lprate(1)
    // effects
    .room(0.345)
    .roomsize(0.5),
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.5)
    .unison(7)
    .detune(3.122)
    .spread(0.8)
    .gain(0.692)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.976)
    // filter
    .cutoff(46)
    .resonance(2.857)
    // modulation
    .lpsync(16)
    .lpdepth(1365)
    .lpdc(0)
    .lprate(1)
    // effects
    .room(0.345)
    .roomsize(0.5),
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.5)
    .unison(8)
    .detune(2.372)
    .spread(0.8)
    .gain(0.727)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.976)
    // filter
    .cutoff(46)
    .resonance(2.857)
    // modulation
    .lpsync(16)
    .lpdepth(1365)
    .lpdc(0)
    .lprate(1)
    // effects
    .room(0.345)
    .roomsize(0.5)
)

// === Unmapped modulations (Vital-specific) ===
// velocity → filter_1_cutoff (amount: 0.381)
// macro_control_1 → filter_1_cutoff (amount: 0.828)
// macro_control_2 → distortion_mix (amount: 1)
// velocity → macro_control_2 (amount: -0.36)
// macro_control_3 → osc_3_wave_frame (amount: 0.7)
// macro_control_3 → osc_2_wave_frame (amount: 0.836)
// macro_control_3 → osc_1_wave_frame (amount: 0.22)
// macro_control_4 → flanger_dry_wet (amount: 1)