// Vital Preset: Snowcrash
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "snowcrash_osc1": ["snowcrash_osc1.wav"],
  "snowcrash_osc2": ["snowcrash_osc2.wav"],
  "snowcrash_osc3": ["snowcrash_osc3.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("snowcrash_osc1")
    .warp(0.52)
    .warpmode("fold")
    .unison(15)
    .detune(3.69)
    .spread(0.8)
    .gain(0.707)
    // envelope
    .attack(1.313)
    .decay(1)
    .release(1.495)
    // filter
    .bandf(568)
    .bandq(11.118)
    // modulation (osc1)
    .wt(0)
    .wtsync(2)
    .wtdepth(0.219)
    .lpsync(16)
    .lpdepth(636)
    .lpdc(0)
    // effects
    .delay(0.333)
    .delaytime(0.333)
    .delayfeedback(0.5)
    .coarse(4),
  note("c3 e3 g3 b3")
    .s("snowcrash_osc2")
    .gain(0.707)
    // envelope
    .attack(1.313)
    .decay(1)
    .release(1.495)
    // filter
    .bandf(568)
    .bandq(11.118)
    // modulation
    .lpsync(16)
    .lpdepth(636)
    .lpdc(0)
    // effects
    .delay(0.333)
    .delaytime(0.333)
    .delayfeedback(0.5)
    .coarse(4),
  note("c3 e3 g3 b3")
    .s("snowcrash_osc3")
    .unison(16)
    .detune(2.651)
    .spread(0.8)
    .gain(0.707)
    // envelope
    .attack(1.313)
    .decay(1)
    .release(1.495)
    // filter
    .bandf(568)
    .bandq(11.118)
    // modulation
    .lpsync(16)
    .lpdepth(636)
    .lpdc(0)
    // effects
    .delay(0.333)
    .delaytime(0.333)
    .delayfeedback(0.5)
    .coarse(4)
)

// === Unmapped modulations (Vital-specific) ===
// macro_control_1 → modulation_2_amount (amount: 0.282)
// macro_control_1 → modulation_4_amount (amount: 0.051)
// macro_control_1 → modulation_3_amount (amount: 0.067)
// macro_control_1 → filter_1_resonance (amount: 0.303)
// macro_control_1 → modulation_13_amount (amount: 0.164)
// macro_control_1 → modulation_14_amount (amount: 0.103)
// macro_control_1 → modulation_15_amount (amount: -0.183)
// macro_control_1 → modulation_16_amount (amount: 0.076)