// Vital Preset: Space Station
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "space_station_osc1": ["space_station_osc1.wav"],
  "space_station_osc2": ["space_station_osc2.wav"],
  "space_station_osc3": ["space_station_osc3.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("space_station_osc1")
    .warp(0.5)
    .warpmode("bendmp")
    .unison(3)
    .spread(0.8)
    .gain(0.535)
    // envelope
    .attack(0.59)
    .decay(1)
    .release(0.762)
    // filter
    .cutoff(366)
    .resonance(3.168)
    // modulation (osc1)
    .detune(sine.fast(4).range(1.32, 3.36))
    .lpsync(4)
    .lpdepth(18000)
    .lpdc(0)
    .lpshape("sine")
    .pan(sine.fast(4).range(0.335, 0.665))
    // effects
    .delay(0.655)
    .delaytime(0.145)
    .delayfeedback(-0.62),
  note("c3 e3 g3 b3")
    .s("space_station_osc2")
    .warpmode("sync")
    .gain(0.442)
    // envelope
    .attack(0.59)
    .decay(1)
    .release(0.762)
    // filter
    .cutoff(366)
    .resonance(3.168)
    // modulation (osc2)
    .warp(0.5)
    .warpsync(2)
    .warpdepth(0.52)
    .warpshape("sine")
    .lpsync(4)
    .lpdepth(18000)
    .lpdc(0)
    .lpshape("sine")
    .pan(sine.fast(4).range(0.335, 0.665))
    // effects
    .delay(0.655)
    .delaytime(0.145)
    .delayfeedback(-0.62),
  note("c3 e3 g3 b3")
    .s("space_station_osc3")
    .warp(0.095)
    .warpmode("bendm")
    .unison(7)
    .spread(0.8)
    .gain(0.235)
    // envelope
    .attack(0.59)
    .decay(1)
    .release(0.762)
    // filter
    .cutoff(366)
    .resonance(3.168)
    // modulation (osc3)
    .detune(sine.fast(4).range(1.2, 3.6))
    .tremolosync(2)
    .tremolodepth(0.575)
    .lpsync(4)
    .lpdepth(18000)
    .lpdc(0)
    .lpshape("sine")
    .pan(sine.fast(4).range(0.335, 0.665))
    // effects
    .delay(0.655)
    .delaytime(0.145)
    .delayfeedback(-0.62)
)

// === Unmapped modulations (Vital-specific) ===
// lfo_2 → distortion_drive (amount: 0.536)
// lfo_1 → filter_1_drive (amount: 0.85)
// macro_control_3 → osc_1_distortion_amount (amount: -0.36)
// macro_control_2 → reverb_dry_wet (amount: 0.577)
// macro_control_2 → reverb_decay_time (amount: 0.282)
// macro_control_3 → osc_3_distortion_amount (amount: -0.405)
// macro_control_4 → osc_1_spectral_morph_amount (amount: 0.25)
// macro_control_4 → modulation_17_amount (amount: 0.234)