// Vital Preset: Special Glitch Thing
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
note("c3 e3 g3 b3")
  .s("sawtooth")
  .gain(0.707)
  // envelope
  .attack(0.149)
  .decay(1)
  .release(1.023)
  // filter
  .cutoff(12)
  // modulation
  .warp(0.5)
  .warprate(0.5)
  .warpdepth(1)
  .wt(1)
  .wtrate(0.5)
  .wtdepth(1)
  .lprate(0.5)
  .lpdepth(1363)
  .lpdc(0)
  .resonance(tri.slow(4).range(0, 0))

// === Unmapped modulations (Vital-specific) ===
// random_1 → osc_1_distortion_amount (amount: 1)
// random_2 → osc_1_unison_detune (amount: 1)
// lfo_1 → osc_1_detune_power (amount: 1)
// random_3 → delay_frequency (amount: -0.67)
// macro_control_4 → distortion_mix (amount: 1)
// lfo_1 → filter_1_blend (amount: 1)
// random_4 → flanger_center (amount: 0.743)
// lfo_4 → filter_1_blend_transpose (amount: 0.895)