// Vital Preset: Squish Clicker
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "squish_clicker_osc1": ["squish_clicker_osc1.wav"],
})

// Pattern — change the notes to taste!
note("c3 e3 g3 b3")
  .s("squish_clicker_osc1")
  .warp(0.5)
  .gain(0.707)
  // envelope
  .attack(0.149)
  .decay(1)
  .release(0.548)
  // filter
  .cutoff(215)
  .resonance(17.045)
  // modulation
  .lpsync(8)
  .lpdepth(18000)
  .lpdc(0)
  // effects
  .shape(0.23)

// === Unmapped modulations (Vital-specific) ===
// lfo_1 → osc_1_transpose (amount: -0.54)
// lfo_3 → filter_1_blend (amount: 0.79)
// macro_control_1 → osc_1_spectral_morph_amount (amount: 0.5)
// macro_control_2 → delay_dry_wet (amount: 1)
// macro_control_3 → osc_1_transpose (amount: 0.812)