// Vital Preset: Staggered Phrases
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "staggered_phrases_osc3": ["staggered_phrases_osc3.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .unison(14)
    .detune(1.32)
    .spread(0.8)
    .pan(0.785)
    .gain(0.707)
    // envelope
    .attack(0.329)
    .decay(1)
    .release(0.548)
    // filter
    .cutoff(1589)
    .resonance(11.489)
    .ftype("ladder")
    // modulation (osc1)
    .wt(0)
    .wtsync(16)
    .wtdepth(1)
    .wtshape("sine")
    // effects
    .shape(0.119)
    .coarse(4),
  note("c3 e3 g3 b3")
    .s("staggered_phrases_osc3")
    .wt(0.335)
    .warp(0.5)
    .pan(0)
    // envelope
    .attack(0.329)
    .decay(1)
    .release(0.548)
    // filter
    .cutoff(1589)
    .resonance(11.489)
    .ftype("ladder")
    // effects
    .shape(0.119)
    .coarse(4)
)

// === Unmapped modulations (Vital-specific) ===
// lfo_2 → lfo_1_tempo (amount: 0.552)
// lfo_1 → distortion_drive (amount: -0.862)
// macro_control_1 → filter_1_blend (amount: 0.502)
// macro_control_2 → filter_1_drive (amount: 0.771)
// lfo_3 → modulation_1_amount (amount: 1)
// mod_wheel → modulation_8_amount (amount: 0.433)
// macro_control_3 → distortion_filter_cutoff (amount: -0.485)
// macro_control_3 → distortion_filter_resonance (amount: 0.65)