// Vital Preset: Strings Section
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "strings_section_osc1": ["strings_section_osc1.wav"],
  "strings_section_osc2": ["strings_section_osc2.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("strings_section_osc1")
    .unison(7)
    .spread(0.8)
    .gain(0.707)
    // envelope
    .attack(0.899)
    .decay(1.544)
    .sustain(0.656)
    .release(1.19)
    // filter
    .cutoff(469)
    .lpenv(1.505)
    .lpattack(0.911)
    .lpdecay(1.455)
    .lpsustain(0.224)
    .lprelease(0.548)
    // modulation (osc1)
    .detune(tri.slow(4).range(1.864, 2.271))
    // effects
    .delay(0.113)
    .delaytime(0.25)
    .delayfeedback(0.33)
    .shape(0.05),
  note("c3 e3 g3 b3")
    .s("strings_section_osc2")
    .warp(0.36)
    .warpmode("asym")
    .unison(7)
    .detune(3.15)
    .spread(0.8)
    .gain(0.707)
    // envelope
    .attack(0.899)
    .decay(1.544)
    .sustain(0.656)
    .release(1.19)
    // filter
    .cutoff(469)
    .lpenv(1.505)
    .lpattack(0.911)
    .lpdecay(1.455)
    .lpsustain(0.224)
    .lprelease(0.548)
    // effects
    .delay(0.113)
    .delaytime(0.25)
    .delayfeedback(0.33)
    .shape(0.05)
)

// === Unmapped modulations (Vital-specific) ===
// velocity → osc_1_level (amount: 0.69)
// velocity → osc_2_level (amount: 0.943)
// macro_control_1 → filter_1_cutoff (amount: 0.116)
// macro_control_2 → env_1_attack (amount: 0.237)
// lfo_1 → lfo_2_frequency (amount: 0.18)
// macro_control_3 → reverb_dry_wet (amount: 0.6)
// macro_control_3 → reverb_decay_time (amount: 0.395)
// macro_control_4 → distortion_drive (amount: 0.475)