// Vital Preset: Super Nice Pluck
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "super_nice_pluck_osc2": ["super_nice_pluck_osc2.wav"],
})

// Pattern — change the notes to taste!
note("c3 e3 g3 b3")
  .s("super_nice_pluck_osc2")
  .wt(0.352)
  .warp(0.5)
  .unison(13)
  .detune(2.722)
  .spread(0.8)
  .gain(0.275)
  // envelope
  .decay(0.765)
  .sustain(0.005)
  .release(0.919)
  // filter
  .cutoff(133)
  .resonance(10)
  .lpenv(2.989)
  .lpattack(0.149)
  .lpdecay(1)
  .lpsustain(1)
  .lprelease(0.548)
  // effects
  .shape(0.38)

// === Unmapped modulations (Vital-specific) ===
// env_1 → compressor_mix (amount: 0.395)
// random_1 → osc_1_wave_frame (amount: 0.62)
// random_1 → osc_1_spectral_morph_amount (amount: 0.14)
// random_1 → osc_1_distortion_amount (amount: 0.5)
// env_1 → osc_1_level (amount: 0.19)
// env_1 → osc_2_level (amount: 0.43)
// macro_control_1 → env_1_decay (amount: 0.153)
// macro_control_1 → env_1_release (amount: 0.304)