// Vital Preset: Super Pluck
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
note("c3 e3 g3 b3")
  .s("sawtooth")
  .warp(0.5)
  .unison(7)
  .detune(4.422)
  .spread(0.8)
  .gain(0.707)
  // envelope
  .decay(1.035)
  .sustain(0.005)
  .release(0.666)
  // modulation
  .wtenv(0.08)
  .wtdecay(1.035)
  .wtrelease(0.666)
  // effects
  .shape(0.41)

// === Unmapped modulations (Vital-specific) ===
// env_1 → osc_2_level (amount: 0.793)
// macro_control_1 → env_1_decay (amount: 0.53)
// env_1 → osc_1_unison_detune (amount: -0.557)
// macro_control_2 → modulation_2_amount (amount: 0.5)
// macro_control_2 → modulation_3_amount (amount: 0.5)
// macro_control_2 → modulation_9_amount (amount: 0.312)
// macro_control_2 → modulation_11_amount (amount: 0.312)
// env_3 → chorus_delay_1 (amount: -0.58)