// Vital Preset: Swiss Army Knife
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "swiss_army_knife_osc2": ["swiss_army_knife_osc2.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.5)
    .gain(0.707)
    // envelope
    .attack(0.042)
    .decay(1)
    .release(1.011)
    // filter
    .cutoff(68)
    .resonance(12.526)
    .ftype("24db")
    // effects
    .room(0.19)
    .roomsize(0.13)
    .delay(0.05)
    .delaytime(0.25)
    .delayfeedback(0.5)
    .shape(0.13),
  note("c3 e3 g3 b3")
    .s("swiss_army_knife_osc2")
    .wt(0.263)
    .warp(0.5)
    // envelope
    .attack(0.042)
    .decay(1)
    .release(1.011)
    // filter
    .cutoff(68)
    .resonance(12.526)
    .ftype("24db")
    // effects
    .room(0.19)
    .roomsize(0.13)
    .delay(0.05)
    .delaytime(0.25)
    .delayfeedback(0.5)
    .shape(0.13)
)

// === Unmapped modulations (Vital-specific) ===
// note → sample_transpose (amount: 0.61)
// lfo_4 → osc_1_tune (amount: 1)
// lfo_5 → osc_1_tune (amount: 0.05)
// mod_wheel → modulation_3_amount (amount: 0.7)
// mod_wheel → lfo_5_frequency (amount: 0.07)
// lfo_5 → osc_2_tune (amount: 0.017)
// mod_wheel → modulation_7_amount (amount: 0.08)
// mod_wheel → modulation_6_amount (amount: 0.802)