// Vital Preset: Synthetic Quartet
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "synthetic_quartet_osc1": ["synthetic_quartet_osc1.wav"],
  "synthetic_quartet_osc2": ["synthetic_quartet_osc2.wav"],
  "synthetic_quartet_osc3": ["synthetic_quartet_osc3.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("synthetic_quartet_osc1")
    .wt(0.016)
    .warp(0.575)
    .warpmode("sync")
    // envelope
    .attack(1.006)
    .decay(1.226)
    .sustain(0.61)
    .release(0.678)
    // filter
    .cutoff(479)
    .ftype("24db")
    // effects
    .room(0.5)
    .roomsize(1)
    .delay(0.198)
    .delaytime(0.333)
    .delayfeedback(0.489)
    .shape(0.04),
  note("c3 e3 g3 b3")
    .s("synthetic_quartet_osc2")
    .wt(0.496)
    .warp(0.696)
    .warpmode("sync")
    .gain(0.64)
    // envelope
    .attack(1.006)
    .decay(1.226)
    .sustain(0.61)
    .release(0.678)
    // filter
    .cutoff(479)
    .ftype("24db")
    // effects
    .room(0.5)
    .roomsize(1)
    .delay(0.198)
    .delaytime(0.333)
    .delayfeedback(0.489)
    .shape(0.04),
  note("c3 e3 g3 b3")
    .s("synthetic_quartet_osc3")
    .warp(0.5)
    .warpmode("bendm")
    .gain(0.815)
    // envelope
    .attack(1.006)
    .decay(1.226)
    .sustain(0.61)
    .release(0.678)
    // filter
    .cutoff(479)
    .ftype("24db")
    // effects
    .room(0.5)
    .roomsize(1)
    .delay(0.198)
    .delaytime(0.333)
    .delayfeedback(0.489)
    .shape(0.04)
)

// === Unmapped modulations (Vital-specific) ===
// velocity → env_1_attack (amount: -0.093)
// env_3 → modulation_1_amount (amount: 0.18)
// env_3 → modulation_3_amount (amount: 0.18)
// macro_control_4 → reverb_decay_time (amount: 0.144)
// env_3 → lfo_2_frequency (amount: 0.038)
// env_3 → modulation_8_amount (amount: 0.164)
// macro_control_1 → osc_2_distortion_amount (amount: -0.329)
// macro_control_2 → osc_1_spectral_morph_amount (amount: 0.114)