// Vital Preset: Text To Wavetable Template
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
note("c3 e3 g3 b3")
  .s("sawtooth")
  .warp(0.5)
  .gain(0.707)
  // envelope
  .attack(0.149)
  .decay(1)
  .release(0.548)
  // modulation
  .wt(0)
  .wtsync(8)
  .wtdepth(1)