// Vital Preset: Thumpus
// Auto-generated by vital2strudel

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("triangle")
    .warp(0.58)
    .warpmode("bendm")
    .unison(6)
    .detune(2.472)
    .spread(0.8)
    .gain(0.707)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.548)
    // filter
    .cutoff(18259)
    .ftype("24db")
    // modulation (osc1)
    .wt(0)
    .wtsync(0.125)
    .wtdepth(1)
    .lpsync(0.125)
    .lpdepth(2836)
    .lpdc(0),
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.5)
    .gain(0.707)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.548)
    // filter
    .cutoff(18259)
    .ftype("24db")
    // modulation (osc2)
    .wt(0)
    .wtsync(0.125)
    .wtdepth(0.59)
    .lpsync(0.125)
    .lpdepth(2836)
    .lpdc(0),
  note("c3 e3 g3 b3")
    .s("sawtooth")
    .warp(0.5)
    .gain(0.645)
    // envelope
    .attack(0.149)
    .decay(1)
    .release(0.548)
    // filter
    .cutoff(18259)
    .ftype("24db")
    // modulation (osc3)
    .wt(0.933)
    .wtsync(0.125)
    .wtdepth(0.82)
    .lpsync(0.125)
    .lpdepth(2836)
    .lpdc(0)
)

// === Unmapped modulations (Vital-specific) ===
// lfo_1 → filter_1_blend (amount: 1)
// lfo_2 → lfo_1_phase (amount: 1)
// macro_control_1 → modulation_6_power (amount: 0.5)
// macro_control_2 → osc_3_spectral_morph_amount (amount: 0.15)
// macro_control_2 → osc_1_spectral_morph_amount (amount: 0.33)
// lfo_1 → osc_2_transpose (amount: 0.5)
// macro_control_1 → modulation_11_power (amount: 0.5)
// macro_control_2 → osc_2_spectral_morph_amount (amount: 0.25)