// Vital Preset: THUNK
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "thunk_osc1": ["thunk_osc1.wav"],
})

// Pattern — change the notes to taste!
note("c3 e3 g3 b3")
  .s("thunk_osc1")
  .gain(0.707)
  // envelope
  .attack(0.149)
  .decay(1)
  .release(0.548)
  // filter
  .cutoff(122)
  // modulation
  .lpsync(16)
  .lpdepth(9347)
  .lpdc(0)
  .lpshape("sine")
  // effects
  .shape(0.19)

// === Unmapped modulations (Vital-specific) ===
// lfo_1 → modulation_4_power (amount: -0.537)
// lfo_1 → voice_transpose (amount: 0.272)
// macro_control_1 → modulation_1_amount (amount: 0.46)
// macro_control_2 → modulation_4_amount (amount: 0.146)
// macro_control_3 → osc_1_distortion_amount (amount: 0.265)
// lfo_1 → distortion_drive (amount: 0.16)
// macro_control_4 → filter_fx_mix (amount: 1)