// Vital Preset: Touch Tone
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "touch_tone_osc1": ["touch_tone_osc1.wav"],
  "touch_tone_osc2": ["touch_tone_osc2.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("touch_tone_osc1")
    // envelope
    .attack(0.218)
    .decay(1)
    .release(0.302),
  note("c3 e3 g3 b3")
    .s("touch_tone_osc2")
    // envelope
    .attack(0.218)
    .decay(1)
    .release(0.302)
)

// === Unmapped modulations (Vital-specific) ===
// note_in_octave → osc_1_transpose (amount: 0.5)
// note_in_octave → osc_1_tune (amount: 0.5)
// note_in_octave → osc_2_transpose (amount: 0.5)
// note_in_octave → osc_2_tune (amount: 0.5)
// note_in_octave → modulation_5_amount (amount: -1)
// note_in_octave → modulation_6_amount (amount: -1)