// Vital Preset: VLT Future Gun
// Auto-generated by vital2strudel

// Load wavetables
await tables("/vital-wavetables/", 2048, {
  "_base": "/vital-wavetables/",
  "vlt_future_gun_osc1": ["vlt_future_gun_osc1.wav"],
  "vlt_future_gun_osc2": ["vlt_future_gun_osc2.wav"],
  "vlt_future_gun_osc3": ["vlt_future_gun_osc3.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("vlt_future_gun_osc1")
    .gain(0.277)
    // envelope
    .attack(0.149)
    .decay(0.96)
    .release(0.402)
    // filter
    .cutoff(259)
    // modulation (osc1)
    .warp(0.5)
    .warpsync(64)
    .warpdepth(0.672)
    .tremolosync(64)
    .tremolodepth(0.822)
    .tremoloshape("tri")
    // effects
    .shape(0.377),
  note("c3 e3 g3 b3")
    .s("vlt_future_gun_osc2")
    .warpmode("fold")
    .gain(0.331)
    // envelope
    .attack(0.149)
    .decay(0.96)
    .release(0.402)
    // filter
    .cutoff(259)
    // modulation (osc2)
    .warp(0.622)
    .warpsync(64)
    .warpdepth(0.324)
    .tremolosync(64)
    .tremolodepth(1)
    .tremoloshape("tri")
    // effects
    .shape(0.377),
  note("c3 e3 g3 b3")
    .s("vlt_future_gun_osc3")
    .warp(0.5)
    .gain(0.709)
    // envelope
    .attack(0.149)
    .decay(0.96)
    .release(0.402)
    // filter
    .cutoff(259)
    // effects
    .shape(0.377)
)

// === Unmapped modulations (Vital-specific) ===
// stereo → osc_2_distortion_amount (amount: 0.049)
// macro_control_1 → lfo_1_tempo (amount: 0.148)
// env_1 → reverb_dry_wet (amount: 0.263)
// macro_control_2 → osc_2_distortion_amount (amount: 0.298)
// macro_control_3 → modulation_9_amount (amount: 0.236)
// macro_control_3 → modulation_11_amount (amount: 0.5)
// lfo_2 → osc_3_transpose (amount: 0.5)
// macro_control_4 → osc_2_spectral_morph_amount (amount: 0.309)