// Vital Preset: Kick Drum 1
// Auto-generated by vital2strudel

// Load wavetables
await samples({
  "_base": "/vital-wavetables/",
  "kick_drum_1_osc1": ["kick_drum_1_osc1.wav"],
})

// Pattern — change the notes to taste!
note("a1 db2 e2 ab2")
  .s("kick_drum_1_osc1")
  .gain(0.774)
  // envelope
  .decay(0.608)
  .sustain(0.0)
  .release(0.334)
  // pitch
  .penv(37.8)
  .pdecay(2.0)
  .pcurve(1)
  // effects
  .shape(0.193)
  .compressor("-10:20:10:.002:.02")

// === Unmapped modulations (Vital-specific) ===
// lfo_3 → distortion_drive (amount: 0.245)
