// Vital Preset: Railgun
// Auto-generated by vital2strudel

// Load wavetables
await samples({
  "_base": "/vital-wavetables/",
  "railgun_osc1": ["railgun_osc1.wav"],
  "railgun_osc2": ["railgun_osc2.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("c3 e3 g3 b3")
    .s("railgun_osc1")
    .gain(0.537)
    // envelope
    .attack(0.149)
    .release(0.548)
    // filter
    .lpf(20000)
    .lpq(9.9)
    // pitch
    .penv(12.6)
    .pattack(0.166)
    .pdecay(0.859)
    .pcurve(1)
    .vib(4.0)
    .vibmod(9.9)
    .tremolosync(4.0)
    .tremolodepth(0.29)
    // effects
    .room(0.065)
    .shape(0.143)
    .compressor("-10:20:10:.002:.02"),
  note("c2 e2 g2 b2")
    .s("railgun_osc2")
    .gain(0.01)
    // envelope
    .attack(0.149)
    .release(0.548)
    // filter
    .lpf(72)
    .lpenv(8.0)
    .lpattack(0.166)
    .lpdecay(0.859)
    .lpsustain(0.0)
    // pitch
    .penv(13.5)
    .pattack(0.166)
    .pdecay(0.859)
    .pcurve(1)
    .vib(4.0)
    .vibmod(10.2)
    .tremolosync(4.0)
    // effects
    .room(0.065)
    .shape(0.143)
    .compressor("-10:20:10:.002:.02")
)

// === Unmapped modulations (Vital-specific) ===
// env_2 → osc_1_unison_voices (amount: 1.0)
// env_2 → filter_fx_cutoff (amount: 0.705)
// env_2 → flanger_center (amount: 1.0)
// lfo_2 → flanger_dry_wet (amount: 1.0)
// lfo_5 → modulation_18_amount (amount: -0.415)
// env_3 → distortion_filter_cutoff (amount: 1.0)
// env_3 → sample_transpose (amount: 0.34)
