// Vital Preset: Smoker's Lounge
// Auto-generated by vital2strudel

// Load wavetables
await samples({
  "_base": "/vital-wavetables/",
  "smokers_lounge_osc1": ["smokers_lounge_osc1.wav"],
  "smokers_lounge_osc2": ["smokers_lounge_osc2.wav"],
  "smokers_lounge_osc3": ["smokers_lounge_osc3.wav"],
})

// Pattern — change the notes to taste!
stack(
  note("eb3 g3 bb3 d4")
    .s("smokers_lounge_osc1")
    .begin(0.396)
    .unison(7)
    .detune(3.622)
    .gain(0.532)
    // envelope
    .attack(0.149)
    .release(0.976)
    // filter
    .lpf(46)
    .lpq(2.9)
    .lpenv(4.8)
    .lpdecay(1.0)
    .lpsustain(0)
    // pitch
    .penv(32.5)
    .pattack(0.149)
    .pdecay(0.358)
    .prelease(0.548)
    .pcurve(1)
    // effects
    .room(0.345)
    .compressor("-10:20:10:.002:.02"),
  note("g3 b3 d4 gb4")
    .s("smokers_lounge_osc2")
    .begin(0.506)
    .unison(7)
    .detune(3.122)
    .gain(0.483)
    // envelope
    .attack(0.149)
    .release(0.976)
    // filter
    .lpf(46)
    .lpq(2.9)
    .lpenv(4.8)
    .lpdecay(1.0)
    .lpsustain(0)
    // effects
    .room(0.345)
    .compressor("-10:20:10:.002:.02"),
  note("bb3 d4 f4 a4")
    .s("smokers_lounge_osc3")
    .begin(0.227)
    .unison(8)
    .detune(2.372)
    .gain(0.508)
    // envelope
    .attack(0.149)
    .release(0.976)
    // filter
    .lpf(46)
    .lpq(2.9)
    .lpenv(4.8)
    .lpdecay(1.0)
    .lpsustain(0)
    // effects
    .room(0.345)
    .compressor("-10:20:10:.002:.02")
)

// === Unmapped modulations (Vital-specific) ===
// lfo_1 → osc_1_wave_frame (amount: 0.106)
// lfo_1 → filter_fx_cutoff (amount: 0.914)
// lfo_2 → distortion_filter_cutoff (amount: 0.435)
