// Vital Preset: Super Nice Pluck
// Auto-generated by vital2strudel

// Load wavetables
await samples({
  "_base": "/vital-wavetables/",
  "super_nice_pluck_osc2": ["super_nice_pluck_osc2.wav"],
})

// Pattern — change the notes to taste!
note("a2 db3 e3 ab3")
  .s("super_nice_pluck_osc2")
  .begin(0.354)
  .unison(13)
  .detune(2.722)
  .gain(0.223)
  // envelope
  .decay(0.765)
  .sustain(0.005)
  .release(0.919)
  // effects
  .shape(0.713)

// === Unmapped modulations (Vital-specific) ===
// random_1 → osc_1_wave_frame (amount: 0.62)
// random_1 → osc_1_spectral_morph_amount (amount: 0.14)
// random_1 → osc_1_distortion_amount (amount: 0.5)
// macro_control_1 → env_1_decay (amount: 0.153)
// macro_control_1 → env_1_release (amount: 0.304)
// macro_control_1 → env_1_sustain (amount: 0.395)
